CREATE OR REPLACE NONEDITIONABLE TYPE mdsys.SDO_PATH_T
  AUTHID current_user
  AS OBJECT(

  object_id   INTEGER,

  NOT INSTANTIABLE MEMBER FUNCTION get_cost(
    net_mem VARCHAR2, path_id NUMBER)
    RETURN NUMBER DETERMINISTIC,

  NOT INSTANTIABLE MEMBER FUNCTION get_no_of_links(
    net_mem VARCHAR2, path_id NUMBER)
    RETURN NUMBER DETERMINISTIC,

  NOT INSTANTIABLE MEMBER FUNCTION get_type(
    net_mem VARCHAR2, path_id NUMBER)
    RETURN VARCHAR2 DETERMINISTIC,

  NOT INSTANTIABLE MEMBER FUNCTION get_name(
    net_mem VARCHAR2, path_id NUMBER)
    RETURN VARCHAR2 DETERMINISTIC,

  NOT INSTANTIABLE MEMBER FUNCTION get_start_node_id(
    net_mem VARCHAR2, path_id NUMBER)
    RETURN NUMBER DETERMINISTIC,

  NOT INSTANTIABLE MEMBER FUNCTION get_end_node_id(
    net_mem VARCHAR2, path_id NUMBER)
    RETURN NUMBER DETERMINISTIC,

  NOT INSTANTIABLE MEMBER FUNCTION get_geometry(
    net_mem VARCHAR2, path_id NUMBER)
    RETURN SDO_GEOMETRY DETERMINISTIC,

  NOT INSTANTIABLE MEMBER FUNCTION get_node_ids(
    net_mem VARCHAR2, path_id NUMBER)
    RETURN SDO_NUMBER_ARRAY DETERMINISTIC,

  NOT INSTANTIABLE MEMBER FUNCTION get_link_ids(
    net_mem VARCHAR2, path_id NUMBER)
    RETURN SDO_NUMBER_ARRAY DETERMINISTIC,

  NOT INSTANTIABLE MEMBER PROCEDURE set_type(
    net_mem VARCHAR2, path_id NUMBER, type VARCHAR2),

  NOT INSTANTIABLE MEMBER PROCEDURE set_name(
    net_mem VARCHAR2, path_id NUMBER, path_name VARCHAR2),

  NOT INSTANTIABLE MEMBER PROCEDURE set_path_id(
    net_mem VARCHAR2, path_id NUMBER, new_path_id NUMBER),

  NOT INSTANTIABLE MEMBER PROCEDURE set_geometry(
    net_mem VARCHAR2, path_id NUMBER,    geom SDO_GEOMETRY),

  NOT INSTANTIABLE MEMBER FUNCTION is_closed(
    net_mem VARCHAR2, path_id NUMBER)
    RETURN VARCHAR2 DETERMINISTIC,

  NOT INSTANTIABLE MEMBER FUNCTION is_connected(
    net_mem VARCHAR2, path_id NUMBER)
    RETURN VARCHAR2 DETERMINISTIC,

  NOT INSTANTIABLE MEMBER FUNCTION is_simple(
    net_mem VARCHAR2, path_id NUMBER)
    RETURN VARCHAR2 DETERMINISTIC,

  NOT INSTANTIABLE MEMBER FUNCTION is_temporary(
    net_mem VARCHAR2, path_id NUMBER)
    RETURN VARCHAR2 DETERMINISTIC,

  NOT INSTANTIABLE MEMBER FUNCTION is_logical(
    net_mem VARCHAR2, path_id NUMBER)
    RETURN VARCHAR2 DETERMINISTIC,

  NOT INSTANTIABLE MEMBER FUNCTION is_active(
    net_mem VARCHAR2, path_id NUMBER)
    RETURN VARCHAR2 DETERMINISTIC,

  NOT INSTANTIABLE MEMBER PROCEDURE compute_geometry(
    net_mem VARCHAR2, path_id NUMBER,    tolerance NUMBER)
) NOT INSTANTIABLE NOT FINAL
/