CREATE OR REPLACE NONEDITIONABLE TYPE mdsys.SDO_GEOMETRY               AS OBJECT (
           SDO_GTYPE       NUMBER,
           SDO_SRID        NUMBER,
           SDO_POINT       SDO_POINT_TYPE,
           SDO_ELEM_INFO   SDO_ELEM_INFO_ARRAY,
           SDO_ORDINATES   SDO_ORDINATE_ARRAY,
           MEMBER FUNCTION  GET_GTYPE
           RETURN NUMBER DETERMINISTIC,
           MEMBER FUNCTION  GET_DIMS
           RETURN NUMBER DETERMINISTIC,
           MEMBER FUNCTION  GET_LRS_DIM
           RETURN NUMBER DETERMINISTIC)
 
  ALTER TYPE SDO_GEOMETRY
  ADD MEMBER FUNCTION GET_WKB RETURN BLOB DETERMINISTIC,
  ADD MEMBER FUNCTION GET_WKT RETURN CLOB DETERMINISTIC,
  ADD MEMBER FUNCTION ST_CoordDim RETURN SMALLINT DETERMINISTIC,
  ADD MEMBER FUNCTION ST_IsValid RETURN INTEGER DETERMINISTIC,
  ADD CONSTRUCTOR FUNCTION SDO_GEOMETRY(wkt IN CLOB,
            srid IN INTEGER DEFAULT NULL) RETURN SELF AS RESULT,
  ADD CONSTRUCTOR FUNCTION SDO_GEOMETRY(wkt IN VARCHAR2,
            srid IN INTEGER DEFAULT NULL) RETURN SELF AS RESULT,
  ADD CONSTRUCTOR FUNCTION SDO_GEOMETRY(wkb IN BLOB,
            srid IN INTEGER DEFAULT NULL) RETURN SELF AS RESULT
  CASCADE
/
CREATE OR REPLACE TYPE BODY mdsys.SDO_GEOMETRY wrapped
a000000
1
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
e
8df 2a1
5YJ6sZLjz00kbvIHhnvQ6D/6mOIwg83Dr0iMfC9Vx7zgSLIJjfEA3/z7hjdU9oqXHIOL27W1
lUrw1vsCET0M1TLH43AZTjR4QYh9mxjK2DSpnJ8Rs59aueGXu6Z7ijZ7ESNet8I5Dumrowa2
dHsaGYh8EF2iIrbh55cvYX3cdtO0xYLWQQ9gkM4lk73Gwno1FBpG856As4XrSNkCw5CaZfNL
BRxmZcSl25vVc91YXTgMD9osen6TWqV5H+q4eRQ6da+xxghR3McTvUW/zK/B+Cz3AJ55RFoU
9ZBll7flgJ0xo2Y5ugA+EMr9ZXGw4LvMeOm8drSOY1ajqtyJ36IgWiOrJ/aQcdJqv408z3O1
G9fTB3qcri/GBrwamyCNK2XV6IeaH8OyimRtn+O9xRXezUC/6RfRQIIQaVbk85eEkxyZMDdb
wAAijmcXdscul8ZSZWkSceHekVOeb0GxatNB6z2RwenXIqb4MMgF3QGVbyLUqb/yQFriDSYj
Lnpzox+YlRDmQzo9WyFiRMEPEVbEZg7e7waOIf+fba2PweDYFz3izv3Qi30YiPAXG50752Tf
dNl7XF/idU0t/Yneiqyt6ep+QQwBU8Y/r0FRTpD5z9YZxepP1f74qre8F7eiEQfOFWLTAzn0
LCUOpf4eloiBYl4=
/