CREATE OR REPLACE NONEDITIONABLE TYPE mdsys.ST_ANNOTATIONTEXTELEMENT
                                                                              
    AS OBJECT (
      privateValue  VARCHAR2(4000),
      privateLocation SDO_GEOMETRY,
      privateLeaderLine SDO_GEOMETRY,
      privateTextAttributes VARCHAR2(4000),
      MEMBER FUNCTION Value Return VARCHAR2,
    MEMBER FUNCTION Value(Value VARCHAR2)  RETURN ST_ANNOTATIONTEXTELEMENT,
    MEMBER FUNCTION Location Return SDO_GEOMETRY,
    MEMBER FUNCTION Location(Location SDO_GEOMETRY)
                  RETURN ST_ANNOTATIONTEXTELEMENT,
    MEMBER FUNCTION LeaderLine Return SDO_GEOMETRY,
    MEMBER FUNCTION LeaderLine(LeaderLine SDO_GEOMETRY)
         RETURN ST_ANNOTATIONTEXTELEMENT,
    MEMBER FUNCTION TextAttributes Return VARCHAR2,
    MEMBER FUNCTION TextAttributes(TextAttributes VARCHAR2)
       RETURN ST_ANNOTATIONTEXTELEMENT)  
/
CREATE OR REPLACE TYPE BODY mdsys.ST_ANNOTATIONTEXTELEMENT IS
 MEMBER FUNCTION Value Return VARCHAR2 is
 BEGIN
  RETURN SELF.privateValue;
 END;

 MEMBER FUNCTION Value(Value VARCHAR2)  RETURN ST_ANNOTATIONTEXTELEMENT IS
 BEGIN
  RETURN ST_ANNOTATIONTEXTELEMENT(value, SELF.PRIVATELOCATION,
           SELF.PRIVATELEADERLINE, SELF.PRIVATETEXTATTRIBUTES);
 END;

 MEMBER FUNCTION Location Return SDO_GEOMETRY is
 BEGIN
  RETURN SELF.privateLocation;
 END;

 MEMBER FUNCTION Location(Location SDO_GEOMETRY)
    RETURN ST_ANNOTATIONTEXTELEMENT IS
 BEGIN
  RETURN ST_ANNOTATIONTEXTELEMENT(SELF.Value, LOCATION,
           SELF.PRIVATELEADERLINE, SELF.PRIVATETEXTATTRIBUTES);
 END;

 MEMBER FUNCTION LeaderLine Return SDO_GEOMETRY is
 BEGIN
  RETURN SELF.privateLeaderLine;
 END;

 MEMBER FUNCTION LeaderLine(LeaderLine SDO_GEOMETRY)
     RETURN ST_ANNOTATIONTEXTELEMENT IS
 BEGIN
  RETURN ST_ANNOTATIONTEXTELEMENT(SELF.Value, SELF.PRIVATELOCATION,
           LEADERLINE, SELF.PRIVATETEXTATTRIBUTES);
 END;

 MEMBER FUNCTION TextAttributes Return VARCHAR2 is
 BEGIN
  RETURN SELF.privateTextAttributes;
 END;

 MEMBER FUNCTION TextAttributes(TextAttributes VARCHAR2)
  RETURN ST_ANNOTATIONTEXTELEMENT IS
 BEGIN
  RETURN ST_ANNOTATIONTEXTELEMENT(SELF.Value, SELF.PRIVATELOCATION,
           SELF.PRIVATELEADERLINE, TEXTATTRIBUTES);
 END;
END;
/