CREATE OR REPLACE NONEDITIONABLE TYPE mdsys.ST_ANNOTATIONTEXTELEMENT_ARRAY
                                                                              
    AS OBJECT (
     privateArray  ST_ANNOT_TEXTELEMENT_ARRAY ,
    MEMBER FUNCTION ElementN ( aposition INTEGER)
          RETURN ST_ANNOTATIONTEXTELEMENT,
    MEMBER FUNCTION ElementN ( element ST_ANNOTATIONTEXTELEMENT, aposition INTEGER)  RETURN ST_ANNOTATIONTEXTELEMENT_ARRAY )  
/
CREATE OR REPLACE TYPE BODY mdsys.ST_ANNOTATIONTEXTELEMENT_ARRAY IS
 MEMBER FUNCTION ElementN ( aposition INTEGER)
    RETURN ST_ANNOTATIONTEXTELEMENT IS
 BEGIN
   IF (aposition > SELF.PRIVATEARRAY.count) THEN
        RETURN NULL;
   END IF;
   RETURN SELF.PRIVATEARRAY(aposition);
 END;

 MEMBER FUNCTION ElementN (element ST_ANNOTATIONTEXTELEMENT, aposition INTEGER)
    RETURN ST_ANNOTATIONTEXTELEMENT_ARRAY IS
  tarray ST_ANNOT_TEXTELEMENT_ARRAY;
 BEGIN
   tarray := SELF.PRIVATEARRAY;
   IF (aposition > SELF.PRIVATEARRAY.count) THEN
        RETURN NULL;
   END IF;
   tarray(aposition) := element;
   RETURN ST_ANNOTATIONTEXTELEMENT_ARRAY(tarray);
 END;
END;
/