CREATE OR REPLACE NONEDITIONABLE TYPE mdsys.ST_CURVEPOLYGON
                                       UNDER ST_SURFACE (
  CONSTRUCTOR FUNCTION ST_CURVEPOLYGON(acurve ST_CURVE) RETURN SELF AS RESULT,
  CONSTRUCTOR FUNCTION ST_CURVEPOLYGON(acurve ST_CURVE, acurvearray
    ST_CURVE_ARRAY) RETURN SELF AS RESULT,
  CONSTRUCTOR FUNCTION ST_CURVEPOLYGON(acurve ST_CURVE, asrid INTEGER)
              RETURN SELF AS RESULT,
  CONSTRUCTOR FUNCTION ST_CURVEPOLYGON(acurve ST_CURVE, acurvearray
             ST_CURVE_ARRAY, asrid INTEGER) RETURN SELF AS RESULT,
  MEMBER FUNCTION ST_ExteriorRing RETURN ST_Curve DETERMINISTIC,
  MEMBER FUNCTION ST_ExteriorRing(acurve ST_Curve)
            RETURN ST_CurvePolygon DETERMINISTIC,
  MEMBER FUNCTION ST_InteriorRings RETURN ST_Curve_Array DETERMINISTIC,
  MEMBER FUNCTION ST_InteriorRings(acurvearray ST_Curve_Array)
          RETURN ST_CurvePolygon DETERMINISTIC,
  MEMBER FUNCTION ST_NumInteriorRing RETURN INTEGER DETERMINISTIC,
  MEMBER FUNCTION ST_InteriorRingN(aposition INTEGER)
     RETURN ST_Curve DETERMINISTIC
--  MEMBER FUNCTION ST_CurvePolyToPoly RETURN ST_Polygon
) NOT FINAL
/
CREATE OR REPLACE TYPE BODY mdsys.ST_CURVEPOLYGON wrapped
a000000
1
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
e
c28 333
3N38gYhUS3JMceWb2SLTAGuPO40wg80r10oFyi+5Qk+s7zxFPBvtMj3ySgDo7zFw++LsXhm1
Ynsd36/eJRSDVVqN7LdYtU+71s5z5+AXg+24+VBZM0lf6JrVjERFSairjJDEXobwlFUa/dAa
rS2JkUmipKKh6shQrE9WWISa9IOzsy7t0FKNuDutFnwdMJiqbPrLjvwvofRkmou4lLo0YN6U
enqxDJLN2dmccfsAdFt3kPcFrIETGsHSqMttXImVl8799fiS0qdg2VlUurosW0Lnxphba9/Q
Ey6AVVFnkLEPMhGQH1wN0zMq+iML1I8f5VmNNpn06Svz/XHFxSnRsSp4l2C3xrzlxvdvbFyh
4ukha8dNSa1x3MTmprqyTX7Na5tAeAE1EsvX7DbWhG2EcQ5op6imO1w3/uhbuh45GAaMDl1W
YaC2KJ6KjN6OwAMsquS25EWqERfoM0/1u9xFbTAjVyxbBJ9LYKTkm3CzVG2jAXBYN2yjyoGp
q5DGG6yL40ARNKBlmIUhKp55HtTZd5E+3y1h/R6+km5BErBkicRmtH/PWP+RhV2TJ7jChfUM
Sd6MsYOTApIDm1PGx14btGkcv+CIHwqEIWtJ3L/mUI/bcKM6+uBDWAsTyIQ34AomnTF22qgX
nLug2u6q3WVyyOPqR9tT01nPb5l5Zf/G5/TNCDCXTq3zLdog/LsE1UQiIBiJuNfDIjicthTJ
UxfQm0oke7v7s16jkeNHGDCZWd7eQgfGksG/XacSj29aVVfuQ3P98GoOJE5uEFCyMkc6NLw7
zsYPTz8dhtdOwA==
/