CREATE OR REPLACE NONEDITIONABLE TYPE mdsys.ST_CURVE
                                        UNDER ST_GEOMETRY (
  OVERRIDING MEMBER FUNCTION ST_Dimension RETURN Integer DETERMINISTIC,
  MEMBER FUNCTION ST_Points RETURN ST_Point_Array DETERMINISTIC,
  MEMBER FUNCTION ST_NumPoints RETURN INTEGER DETERMINISTIC,
  MEMBER FUNCTION ST_PointN(aposition INTEGER) RETURN ST_Point DETERMINISTIC,
  MEMBER FUNCTION ST_IsClosed RETURN Integer DETERMINISTIC,
  MEMBER FUNCTION ST_MidPointRep RETURN ST_Point_Array DETERMINISTIC,
  MEMBER FUNCTION ST_StartPoint RETURN ST_Point DETERMINISTIC,
  MEMBER FUNCTION ST_EndPoint RETURN ST_Point DETERMINISTIC,
  OVERRIDING MEMBER FUNCTION ST_IsSimple RETURN Integer DETERMINISTIC,
  MEMBER FUNCTION ST_IsRing RETURN Integer DETERMINISTIC,
  MEMBER FUNCTION ST_Length RETURN NUMBER DETERMINISTIC) NOT FINAL
/
CREATE OR REPLACE TYPE BODY mdsys.ST_Curve wrapped
a000000
1
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
e
a1c 38c
o/s16YvGnEeLq6S/StPE1RjVcCEwgz0rLiAFfHRVrZ2sgN728MnGiABX34bnyGyEUZjOiev5
3anN/tDCkcbckKCIUITHWnD0z8/P5LhNIPOfYfyv6ybkTvi7lmk/HXAPUK1cPl6E1tfLpIra
XvHCGwQr5TWGOjdiasaoMv+pZUYqEytafasBiUlcYDSkPMWjCu1Ns9/PdOjro+GkUF/n0AV2
UMN+iSDJ3QWljv/BLU6yLOLI9mJO53+3TjD1xW7VkirApgHBNDIvTMaEptCrDKyGHdIpkbt1
e5Ta8BXqM3f3JZPw2yd/qyOvHPhWXUkBm0vi4KyYHMNEApYLh68VD3xteCfDfw9Nb6Q/eg/O
561q2aVaVgld3Z/o9uDm5pc12Kn/L66zF3K92pG9R3XEYWEu2FuERJpR0l7na11uRnC1Xz29
JHMdWfoXNf1yc7d9AiVEpdtmlMlnWY3tK1lDDHkAKxP+IYipi0GeBAwI9Y96CAasFl4vklkf
QZstPl7spgYNY7TyVIQvqxw42o2rDnw9Lm676lLOgu5WF2Zcpg3GCH0pVvZuiSH9jKOxd257
4MeaR0q3IR4wQKPeknjlrTZ4zPxRDYeyH/SszwDCHuki/xh0UGSnei7RArkaVtyWHYNOVpp/
+mfWxnIde3QL5M8bLK1WoqsX76JFe7Z4oifDKqZXfruT4IFpQS+9+oEfBQsEg/Wk9Hw7XhdX
Xa2zoqeELcuRKkUViRZObYryQ5fcH/+3hrHWTQHfYlV4ZU7DV6tWJMwmxCxp4LySfmXYNMMi
ZwTw6Ohqk6d1fZic647VBuN4RXt51xHPc7KOg+QkH8m4/uXek8C9D8HVo4WVGct/4dYFtZhg
S9q0VqN+aMsDCReCtMdSFf6cqshzz48=
/