CREATE OR REPLACE NONEDITIONABLE TYPE mdsys.ST_GEOMCOLLECTION
                                       UNDER ST_GEOMETRY (
  CONSTRUCTOR FUNCTION ST_GEOMCOLLECTION(ageometry ST_GEOMETRY) RETURN SELF AS RESULT,
  CONSTRUCTOR FUNCTION ST_GEOMCOLLECTION(ageometryarray ST_GEOMETRY_ARRAY) RETURN SELF AS RESULT,
  CONSTRUCTOR FUNCTION ST_GEOMCOLLECTION(ageometry ST_GEOMETRY, asrid INTEGER) RETURN SELF AS RESULT,
  CONSTRUCTOR FUNCTION ST_GEOMCOLLECTION(ageometryarray ST_GEOMETRY_ARRAY, asrid INTEGER) RETURN SELF AS RESULT,

  OVERRIDING MEMBER FUNCTION ST_Dimension RETURN Integer DETERMINISTIC,
  MEMBER FUNCTION ST_GEOMETRIES RETURN ST_GEOMETRY_ARRAY DETERMINISTIC,
  MEMBER FUNCTION ST_GEOMETRIES(ageometryarray ST_GEOMETRY_ARRAY) RETURN ST_GEOMCOLLECTION) NOT FINAL
/
CREATE OR REPLACE TYPE BODY mdsys.ST_GEOMCOLLECTION wrapped
a000000
1
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
e
84a 2cd
s5xFWHcYQsUreF589aXtMgNhAjAwg9dcr0gafHTNvg/u7/fo9yNVs+LbqTjvAjZsayeuTrWq
zNr74Tc7dyfLElio/wNz5By97guiUzEzHc9T/hEH1CfwLmk8qZtypvAqIlMmvTw1eFigx90r
RjZNreOvO5XOk1Cnanyt8oRVNc3eKUmkCXP9M5fbfhmNbkSdP8EJf8DwqcMCT7OgscFP8QqQ
Cr90u3+bgkHJJXstHuPW4QEYYMJe/1vIwl8e7BWDg3/JHwEQ9rteaaM8hlpqK3adjpTFbGaH
Gvk2bUMc5T0r6AyDm9wNIcndHFWGNEz78YDQAAT6KLAd+3q0+Qcu/p2885pcdfnN/XuDK+gH
+wf9uVxIPanU6+Do2gwqbVtiOfXWZZdbPRSVtC04oDkupYBb022zI/HIE2MqMjE7WF47gSJu
O2lMw0CS6e82Rp0RbyeWZLEWGPzibP0rdUSX2I6S8nYj00rl2DNlumXOjVVHPcvc/1iIzMxR
yLrznIdSNtS1MaAuC0f4bCySugnEapBVWxNHMcGQ97PStrADZhO2zIO/SFcL+e4y32I3tKzT
xE3T89OaHZ2SHsx9f1DaqasHJxCYAhbLD/JMcnGjpzmVFqRPrEaKbqS5aNDvvn/zUjK2wLGZ
FgiVAG78u5ZkljL5+Uke5B6QKtxTQ8mtne/QAJb25DAQ4zIc+UKSNrwmy1w=
/