CREATE OR REPLACE NONEDITIONABLE TYPE mdsys.ST_LINESTRING
                                      
UNDER ST_CURVE (
  CONSTRUCTOR FUNCTION ST_LINESTRING(apointarray ST_Point_Array)
               RETURN SELF AS RESULT,
  CONSTRUCTOR FUNCTION ST_LINESTRING(apointarray ST_Point_Array, asrid INTEGER)
 RETURN SELF AS RESULT,
  OVERRIDING MEMBER FUNCTION ST_IsSimple RETURN Integer DETERMINISTIC,
  MEMBER FUNCTION ST_Points(apointarray ST_Point_Array) RETURN ST_LineString)
/
CREATE OR REPLACE TYPE BODY mdsys.ST_LINESTRING wrapped
a000000
1
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
e
66e 25c
ahRevgQD+CjVjDyK0KVEglEJ58swgz3DLiDWfHRVvp0VgGZ/wyN2gzesOKfmrPFpjV61tZ11
t2kig9yDGieDU6JhLD9yLPT9EkaM4oBLuWahazJAw5mRv6aNK37Ljes57DVcSqCDBtNg+4nt
G0PyC5fIG1SccJ5K/fXW7rVp32mj383KTBQRx0sNvKBN2vXJVrQyGNF5JwljanXUWyN5NbJV
8/DEGqOIgH6hRGx3Z8IrhPksPkRTKMMvyi+JkUG2GRmEU3XhzN6gaT1uO7RE1jEERfJuXCNp
0WaTf1u76UlR41+yxHIKSUStkVhyGw25SSVeQe4xf0zAL5WKDLSkV4fHUmqQuNH3Uk9yKI8P
rMZjVq4cO5+nP6Q1wLS7KCkbhNHmA2UoA0D8IdJWkFO7IiiE9FUCw4yw3F0pqNfpl+a+SS0+
E6igQncDdKkykoY+DARjp4fact04bYuuzUNkZEOdVZdJ2JrEnNByy3MUeLofJ0skQjO5Tz0B
YmaLe7X4kLw4kxhBmXUgY1SZsUkhik5fKCfK9iYebNFmsLr7KnshpD7CSuUNtC4ATsPJlDin
saC3L7RTn4eD2Unq5eNl
/