CREATE OR REPLACE NONEDITIONABLE TYPE mdsys.ST_MULTIPOINT
                                       UNDER ST_GEOMCOLLECTION (
  CONSTRUCTOR FUNCTION ST_MULTIPOINT(apointarray ST_Point_Array) RETURN SELF AS RESULT,
  CONSTRUCTOR FUNCTION ST_MULTIPOINT(apointarray ST_Point_Array, asrid INTEGER) RETURN SELF AS RESULT,

  OVERRIDING MEMBER FUNCTION ST_Dimension RETURN Integer DETERMINISTIC,
  OVERRIDING MEMBER FUNCTION ST_IsSimple RETURN Integer DETERMINISTIC)
/
CREATE OR REPLACE TYPE BODY mdsys.ST_MULTIPOINT wrapped
a000000
1
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
e
3c5 1b1
KUQ4ZSmJ23eEqAfIYtrf/hj6gG4wg1XMmNzbZ3Qa/+pTWRoLRGJJGHo0ryUiUUxbPlz5tZal
e+5a3I7qacw7AGHGhpOHG0bRy5mRh3OKdehaNzfARFDGyK3XAMY2n8sAXnTBvKNFpqPwBYmj
Y7N+PaD3I+ZBt0drA1DJoQNfIJl7dj4W6Sbs84wHxL/nA8fqAjt+Gw64cThWY0dwR731O3DR
1KHBuedOL7FY+lif7Hx0Mq+Wxgjsq3lIYQ0ljHG6YaRp4K/ZTkk8cWEj3CGFN1/v6KruPPCX
jhwArleB/w/NiXg/4PFlAvN6kstyp8tdf5GhnzuYhJgXfMoLm44WgoH+YPdcgeEKLrKlW0Ag
QMGxCidJEo45lpig67lb9Qn/XUkHPYbTKLXX9vMYbqeSi3ALy6BbXCRpXFbPkuHOZAhT
/