CREATE OR REPLACE NONEDITIONABLE TYPE mdsys.ST_MULTILINESTRING
                                       UNDER ST_MULTICURVE (
  CONSTRUCTOR FUNCTION ST_MULTILINESTRING(alinestringarray ST_LINESTRING_ARRAY)
          RETURN SELF AS RESULT,
  CONSTRUCTOR FUNCTION ST_MULTILINESTRING(alinestringarray ST_LINESTRING_ARRAY,
             asrid INTEGER) RETURN SELF AS RESULT)
/
CREATE OR REPLACE TYPE BODY mdsys.ST_MULTILINESTRING wrapped
a000000
1
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
e
2c7 13c
SsQBiqq9u2JzoQQVs7YFOfQPs0kwg1XINRhqfHTpF1VeEVhnCPujye4b8i9TwMhD6eq+tWJg
p2sC6AVIyQvYZLtJqikLhFNDOvvp/hIu8vQEbZ4InsPcpl7J1R4ak3Amej4B+XAcR54vD+aO
9NwQoZj2jK1EDRg4fGIvbY2VERAZsurgBw1IVH+a7puZcV5FRTS0gOfjKGoV5gmO5lefCaBg
l0LHFf1FR0Jkp2zbeYRBB+hPKF83YKp/Mw91szft/EKDVdIeKf322r8X8+xiNAYYmyx4Ol0C
OU6gOTO0T+pV/08kTP0Dlw==
/