CREATE OR REPLACE NONEDITIONABLE TYPE mdsys.ST_MULTICURVE
                                       UNDER ST_GEOMCOLLECTION (
  CONSTRUCTOR FUNCTION ST_MULTICURVE(acurvearray ST_CURVE_ARRAY) RETURN SELF AS RESULT,
  CONSTRUCTOR FUNCTION ST_MULTICURVE(acurvearray ST_CURVE_ARRAY, asrid INTEGER) RETURN SELF AS RESULT,

  OVERRIDING MEMBER FUNCTION ST_Dimension RETURN Integer DETERMINISTIC,
  OVERRIDING MEMBER FUNCTION ST_IsSimple RETURN Integer DETERMINISTIC,
  MEMBER FUNCTION ST_Length RETURN NUMBER DETERMINISTIC,
  MEMBER FUNCTION ST_IsClosed RETURN Integer DETERMINISTIC) NOT FINAL
/
CREATE OR REPLACE TYPE BODY mdsys.ST_MULTICURVE wrapped
a000000
1
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
e
5b1 26c
Puy/oeKSoTmlkQPybFmv5CbijIswg1VeANDWfHTtWA/u8xrad+IHe2l8dwlaaeDFMvy1tR/B
z2kOsSukSEVin4rBwRcTlu8Vs6AfuM+kG5V3WTNfZ9EdEV+ffrBA8AJIJbK3swVTcVGm/KXi
OzsdWUvir1ZdmmauK5tpMmnaf5AaxuGAiqFb57W6MxE5ziKpQYnlrJi3lzYasWyXStgLFtnw
Xj0GXtRfqLvLUA2Le38mwhyAd3m5c08e0m4YL3HbwtO2S1GU/aUgCOoxT+dOiLWQYyuDC4qz
+Zk7SGljxr3Nvcl9Tlh1i18rvKH+fI+42zsaYrJNkAT09gkW3jliZYM3Ia3z+YcW/OESUltY
no+2/Iju9g9EuXc79K8izAV3y3osyO+xFoZL1xnuQ7HJBPBg1/9JEieFM9MfZvEE8LD8HsMT
3CtYP6KHXUQ3UEOVwh0chGFwu7C8XXOrReOCZJG8RkPxkNS64qtHmVfd0Z51myBiu+Vdkwo6
fazfg/+FchpcTRIiYhVgXIdyErwcMTQFnmBuoJVtuEdgazsy1pUYw3QziYeWbK2Aak18Eqos
6sbtXyKdkAwJ2hVIkexMk4soi4Zb2QL2PA==
/