CREATE OR REPLACE NONEDITIONABLE TYPE mdsys.ST_MULTISURFACE
                                       UNDER ST_GEOMCOLLECTION (
  CONSTRUCTOR FUNCTION ST_MULTISURFACE(asurfacearray ST_SURFACE_ARRAY)
   RETURN SELF AS RESULT,
  CONSTRUCTOR FUNCTION ST_MULTISURFACE(asurfacearray ST_SURFACE_ARRAY,
                  asrid INTEGER) RETURN SELF AS RESULT,

  OVERRIDING MEMBER FUNCTION ST_Dimension RETURN Integer DETERMINISTIC,
  MEMBER FUNCTION ST_PointOnSurface RETURN ST_Point DETERMINISTIC,
  MEMBER FUNCTION ST_Area RETURN NUMBER DETERMINISTIC) NOT FINAL
/
CREATE OR REPLACE TYPE BODY mdsys.ST_MULTISURFACE wrapped
a000000
1
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
abcd
e
495 1f2
GRmZenersx6HkRub3QgNiFIHZQgwg1UJr0jWfHRVvg/u71qkJZ9xDYSeQJOevfJuoQAItap/
xhqkDuKDOLCQrM3BwcEXzmWobhC/N4VOdVZeWWt4YuGVHWceTF3IozP7kl2jG7szhfK4puii
GzaMkWxBKsyZG8qwylUREjUMBAKRiMfUN24lXSeCDizuzaRxwjMaKYeLtsgFSt4jnvdr3p/e
9hT27U+gv4Cr2iRJGwV13uaxXK2qaNPDw9U0h0CZ8jGnEZPvqgwiJKoR6y1w4TLCVoap7iyt
v+/2ZbfRPthFzUz2Q4FPBBpZSKnzxoJIzc0Roh9sFidtrpWtfch/X10WZQ0SmE3qc/ErAyeP
KPXqQMGctyewP2J0h22g1349QoBoXekH5B9t2grVpyULQpnOIwIlCSm9SMtIScNLaIRMp0r7
WO2VcHFtMu0JvHn4oby9EbzpmBqpD1oZ8kdWPR1M1ZOII3tdaiQQ+3plSSQ=
/