CREATE TABLE mdsys.csw_record_types$ (
  recordtypeid NUMBER NOT NULL,
  typename VARCHAR2(80 BYTE),
  typenamens VARCHAR2(2083 BYTE),
  describerecord XMLTYPE,
  datapointer VARCHAR2(61 BYTE),
  idpaths mdsys.stringlist,
  spatialpaths mdsys.stringlist,
  tspaths mdsys.stringlist,
  lastupdatets TIMESTAMP,
  briefxslpattern XMLTYPE,
  summaryxslpattern XMLTYPE,
  dcmixslpattern XMLTYPE,
  srspaths mdsys.stringlist,
  srsns VARCHAR2(2083 BYTE),
  srsnsalias VARCHAR2(80 BYTE),
  rtxsdrefid VARCHAR2(80 BYTE),
  numcols mdsys.stringlist,
  idxpaths mdsys.stringlist,
  idxpathtypes mdsys.stringlist,
  xtidxcreated VARCHAR2(1 BYTE),
  idextractortype VARCHAR2(20 BYTE) CONSTRAINT sdo_csw_idexttype_1 CHECK ( idExtractorType IN ('XPATH', 'USER_FUNC', 'NONE')),
  isgml3 VARCHAR2(1 BYTE),
  spatialarrlist mdsys.stringlistlist,
  spatialpathssrsnslist mdsys.stringlistlist,
  spatialarrpathssrsnslist mdsys.stringlistlist,
  PRIMARY KEY (recordtypeid),
  CONSTRAINT unique_csw_rt_cond UNIQUE (typenamens,typename)
);