CREATE TABLE mdsys.openls_nodes (
  "NAME" VARCHAR2(32 BYTE) NOT NULL,
  "VERSION" VARCHAR2(32 BYTE) NOT NULL,
  openls XMLTYPE NOT NULL,
  CONSTRAINT openls_nodes_prim PRIMARY KEY ("NAME","VERSION")
);