CREATE GLOBAL TEMPORARY TABLE mdsys.sdo_gr_mosaic_0 (
  rid ROWID,
  rdt VARCHAR2(100 BYTE),
  rstid NUMBER,
  rstype NUMBER,
  srid NUMBER,
  rctif VARCHAR2(10 BYTE),
  r0 NUMBER,
  c0 NUMBER,
  b0 NUMBER,
  r1 NUMBER,
  c1 NUMBER,
  b1 NUMBER,
  bands NUMBER,
  bcv NUMBER,
  ilv VARCHAR2(5 BYTE),
  rblksz NUMBER,
  cblksz NUMBER,
  bblksz NUMBER,
  cdl NUMBER,
  cdp VARCHAR2(50 BYTE),
  ultr NUMBER,
  ultc NUMBER,
  ultb NUMBER,
  rrows NUMBER,
  cols NUMBER,
  cptype VARCHAR2(10 BYTE),
  "ID" NUMBER NOT NULL,
  op NUMBER,
  nodata_ind NUMBER,
  dist NUMBER,
  "EXTENT" mdsys.sdo_geometry,
  meta XMLTYPE,
  PRIMARY KEY ("ID")
)
ON COMMIT PRESERVE ROWS;