CREATE TABLE mdsys.sdo_coord_ops (
  coord_op_id NUMBER(10) NOT NULL CONSTRAINT coord_op_id_must_be_pos CHECK (COORD_OP_ID > 10),
  coord_op_name VARCHAR2(80 BYTE) CONSTRAINT coord_op_name_no_legacy_name CHECK (
          COORD_OP_NAME NOT IN (
            'Geographic (Lat/Long)',
            'Universal Transverse Mercator',
            'State Plane Coordinates',
            'Albers Conical Equal Area',
            'Lambert Conformal Conic',
            'Mercator',
            'Polar Stereographic',
            'Polyconic',
            'Equidistant Conic',
            'Transverse Mercator',
            'Stereographic',
            'Lambert Azimuthal Equal Area',
            'Azimuthal Equidistant',
            'Gnomonic',
            'Orthographic',
            'General Vertical Near-Side Perspective',
            'Sinusoidal',
            'Equirectangular',
            'Miller Cylindrical',
            'Van der Grinten',
            'Hotine Oblique Mercator',
            'Robinson',
            'Space Oblique Mercator',
            'Alaska Conformal',
            'Interrupted Goode Homolosine',
            'Mollweide',
            'Interrupted Mollweide',
            'Hammer',
            'Wagner IV',
            'Wagner VII',
            'Oblated Equal Area',
            'Non-earth',
            'Transverse Mercator Danish System 45 Bornholm',
            'Transverse Mercator Danish System 34 Jylland-Fyn',
            'Transverse Mercator Sjaelland',
            'Transverse Mercator Finnish KKJ',
            'Eckert IV',
            'Eckert VI',
            'Gall',
            'Lambert Conformal Conic (Belgium 1972)',
            'New Zealand Map Grid',
            'Cylindrical Equal Area',
            'Swiss Oblique Mercator',
            'Bonne',
            'Cassini')),
  coord_op_type VARCHAR2(24 BYTE),
  source_srid NUMBER(10),
  target_srid NUMBER(10),
  coord_tfm_version VARCHAR2(24 BYTE),
  coord_op_variant NUMBER(5) CONSTRAINT coord_op_variant_must_be_pos CHECK (COORD_OP_VARIANT > 0),
  coord_op_method_id NUMBER(10),
  uom_id_source_offsets NUMBER(10),
  uom_id_target_offsets NUMBER(10),
  information_source VARCHAR2(254 BYTE),
  data_source VARCHAR2(40 BYTE),
  show_operation NUMBER(3) NOT NULL,
  is_legacy VARCHAR2(5 BYTE) NOT NULL,
  legacy_code NUMBER(10),
  reverse_op NUMBER(1),
  is_implemented_forward NUMBER(1),
  is_implemented_reverse NUMBER(1),
  CONSTRAINT coord_op_name_unique UNIQUE (coord_op_name),
  CONSTRAINT coord_op_prim PRIMARY KEY (coord_op_id),
  CONSTRAINT coord_operation_foreign_legacy FOREIGN KEY (legacy_code) REFERENCES mdsys.sdo_coord_ops (coord_op_id),
  CONSTRAINT coord_operation_foreign_method FOREIGN KEY (coord_op_method_id) REFERENCES mdsys.sdo_coord_op_methods (coord_op_method_id),
  CONSTRAINT coord_operation_foreign_source FOREIGN KEY (source_srid) REFERENCES mdsys.sdo_coord_ref_sys (srid),
  CONSTRAINT coord_operation_foreign_target FOREIGN KEY (target_srid) REFERENCES mdsys.sdo_coord_ref_sys (srid)
);