CREATE TABLE mdsys.wfs_featuretype$ (
  featuretypeid NUMBER NOT NULL,
  featuretypename VARCHAR2(80 BYTE),
  featuredesc XMLTYPE,
  describefeaturetype XMLTYPE,
  lastdescribefeaturetypegents TIMESTAMP,
  lastfeatureupdatets TIMESTAMP,
  namespaceprefix VARCHAR2(20 BYTE),
  namespaceurl VARCHAR2(2083 BYTE),
  schemalocation VARCHAR2(2083 BYTE),
  keycols VARCHAR2(4000 BYTE),
  datapointer VARCHAR2(61 BYTE),
  isdocbased VARCHAR2(1 BYTE),
  spatialcols mdsys.stringlist,
  mandatorycols mdsys.stringlist,
  tscols mdsys.stringlist,
  docidpaths mdsys.stringlist,
  spatialpatharrsep mdsys.stringlist,
  primaryspatialcol VARCHAR2(4000 BYTE),
  featuremembername VARCHAR2(2200 BYTE),
  srsns VARCHAR2(2083 BYTE),
  srsnsalias VARCHAR2(80 BYTE),
  ftxsdrefid VARCHAR2(80 BYTE),
  ismtableview VARCHAR2(1 BYTE),
  vtablelist mdsys.stringlist,
  vkeycolslist mdsys.stringlist,
  tkeycolslist mdsys.stringlist,
  numcols mdsys.stringlist,
  idxpaths mdsys.stringlist,
  idxpathtypes mdsys.stringlist,
  xtidxcreated VARCHAR2(1 BYTE),
  featurecollectionname VARCHAR2(2200 BYTE),
  formattedkeycols mdsys.stringlist,
  formattedtkeycollist mdsys.stringlistlist,
  isgml3 VARCHAR2(1 BYTE),
  spatialarrlist mdsys.stringlistlist,
  spatialpathssrsnslist mdsys.stringlistlist,
  spatialarrpathssrsnslist mdsys.stringlistlist,
  wfs_version VARCHAR2(20 BYTE),
  PRIMARY KEY (featuretypeid),
  CONSTRAINT unique_wfs_ft_cond UNIQUE (namespaceurl,featuretypename)
);