CREATE OR REPLACE NONEDITIONABLE TRIGGER
  mdsys.SDO_CRS_DELETE_TRIGGER
INSTEAD OF
  DELETE
ON
  mdsys.SDO_COORD_REF_SYSTEM
FOR EACH ROW
DECLARE
  already_exists  NUMBER;
BEGIN
  DELETE FROM mdsys.SDO_CS_SRS WHERE SRID = :old.SRID;
  DELETE FROM mdsys.SDO_COORD_REF_SYS WHERE SRID = :old.SRID;
  DELETE FROM mdsys.sdo_crs_geographic_plus_height WHERE srid = :old.srid;
END;
/