CREATE OR REPLACE NONEDITIONABLE TRIGGER mdsys.SDO_CRS_GEOG_SRID_UPDATE
AFTER UPDATE OR DELETE ON mdsys.SDO_CRS_GEOGRAPHIC_PLUS_HEIGHT
FOR EACH ROW
BEGIN
  mdsys.mdprvt_srid.sdo_invalidate_srid_metadata(:old.srid);
END;
/