CREATE OR REPLACE NONEDITIONABLE TRIGGER mdsys.SDO_NETWORK_TRIG_DEL
INSTEAD OF DELETE ON mdsys.user_sdo_network_metadata
REFERENCING OLD AS o
FOR EACH ROW
DECLARE
  user_name    VARCHAR2(256);
BEGIN

  EXECUTE IMMEDIATE 'SELECT USER FROM DUAL' INTO user_name;

  DELETE FROM SDO_NETWORK_METADATA_TABLE WHERE NLS_UPPER(SDO_OWNER) = NLS_UPPER(user_name)
  AND NLS_UPPER(network) = NLS_UPPER(:o.network);

END;
/