CREATE OR REPLACE NONEDITIONABLE TRIGGER
  mdsys.SDO_PREFERRED_OPS_SYSTEM_TRIG
BEFORE
  INSERT OR
  UPDATE OR
  DELETE
ON
  mdsys.SDO_PREFERRED_OPS_SYSTEM
FOR EACH ROW
BEGIN
  mdsys.sdo_cs.sdo_cs_context_invalidate;
END;
/