CREATE OR REPLACE FORCE NONEDITIONABLE VIEW mdsys.all_sdo_viewframes ("OWNER","NAME",description,scene_name,definition) AS
SELECT SDO_OWNER OWNER, NAME, DESCRIPTION, SCENE_NAME, DEFINITION
FROM SDO_VIEWFRAMES_TABLE;