CREATE OR REPLACE FORCE NONEDITIONABLE VIEW mdsys.all_sdo_network_metadata ("OWNER","NETWORK",network_id,network_category,geometry_type,network_type,no_of_hierarchy_levels,no_of_partitions,lrs_table_name,lrs_geom_column,node_table_name,node_geom_column,node_cost_column,node_partition_column,node_duration_column,link_table_name,link_geom_column,link_direction,link_cost_column,link_partition_column,link_duration_column,path_table_name,path_geom_column,path_link_table_name,subpath_table_name,subpath_geom_column,partition_table_name,partition_blob_table_name,component_table_name,node_level_table_name,topology,user_defined_data,external_references,child_network,hierarchy_table_name) AS
SELECT SDO_OWNER OWNER,
         NETWORK,
         NETWORK_ID,
         NETWORK_CATEGORY,
         GEOMETRY_TYPE,
         NETWORK_TYPE,
         NO_OF_HIERARCHY_LEVELS,
         NO_OF_PARTITIONS,
         LRS_TABLE_NAME,
         LRS_GEOM_COLUMN,
         NODE_TABLE_NAME,
         NODE_GEOM_COLUMN,
         NODE_COST_COLUMN,
         NODE_PARTITION_COLUMN,
         NODE_DURATION_COLUMN,
         LINK_TABLE_NAME,
         LINK_GEOM_COLUMN,
         LINK_DIRECTION,
         LINK_COST_COLUMN,
         LINK_PARTITION_COLUMN,
         LINK_DURATION_COLUMN,
         PATH_TABLE_NAME,
         PATH_GEOM_COLUMN,
         PATH_LINK_TABLE_NAME,
         SUBPATH_TABLE_NAME,
         SUBPATH_GEOM_COLUMN,
         PARTITION_TABLE_NAME,
         PARTITION_BLOB_TABLE_NAME,
         COMPONENT_TABLE_NAME,
         NODE_LEVEL_TABLE_NAME,
         TOPOLOGY,
         USER_DEFINED_DATA,
         EXTERNAL_REFERENCES,
         CHILD_NETWORK,
         HIERARCHY_TABLE_NAME
        FROM SDO_NETWORK_METADATA_TABLE;