CREATE OR REPLACE FORCE NONEDITIONABLE VIEW mdsys.dba_sdo_styles ("OWNER","NAME","TYPE",description,definition,image,geometry) AS
SELECT SDO_OWNER OWNER, NAME, TYPE, DESCRIPTION,DEFINITION,
IMAGE,GEOMETRY
FROM SDO_STYLES_TABLE;