CREATE OR REPLACE FORCE NONEDITIONABLE VIEW mdsys.sdo_projections_old_format ("NAME") AS
(
  SELECT DISTINCT
    OP.COORD_OP_NAME "NAME"
  FROM
    mdsys.SDO_COORD_REF_SYS CRS,
    mdsys.SDO_COORD_OPS OP
  WHERE
    CRS.PROJECTION_CONV_ID = OP.COORD_OP_ID
UNION
  SELECT
    NAME
  FROM
    mdsys.SDO_PROJECTIONS_OLD_SNAPSHOT);