CREATE OR REPLACE FORCE NONEDITIONABLE VIEW mdsys.sdo_available_ops (source_srid,coord_op_id,target_srid,is_implemented) AS
SELECT SOURCE_SRID, COORD_OP_ID, TARGET_SRID, IS_IMPLEMENTED FROM mdsys.SDO_AVAILABLE_ELEM_OPS
          UNION
          SELECT SOURCE_SRID, COORD_OP_ID, TARGET_SRID, IS_IMPLEMENTED FROM mdsys.SDO_AVAILABLE_NON_ELEM_OPS
      ;