CREATE OR REPLACE FORCE NONEDITIONABLE VIEW mdsys.sdo_available_non_elem_ops (source_srid,coord_op_id,target_srid,is_implemented) AS
SELECT SOURCE_SRID, COORD_OP_ID, TARGET_SRID, IS_IMPLEMENTED_FORWARD "IS_IMPLEMENTED" FROM mdsys.SDO_COORD_OPS WHERE COORD_OP_TYPE = 'CONCATENATED OPERATION'
          UNION
          SELECT TARGET_SRID "SOURCE_SRID", -COORD_OP_ID, SOURCE_SRID "TARGET_SRID", IS_IMPLEMENTED_REVERSE "IS_IMPLEMENTED" FROM mdsys.SDO_COORD_OPS WHERE COORD_OP_TYPE = 'CONCATENATED OPERATION' AND REVERSE_OP = 1
      ;