GRANT SELECT ON mdsys.csw_capabilitiesinfo$ TO csw_usr_role;
GRANT SELECT ON mdsys.csw_domaininfo$ TO csw_usr_role;
GRANT SELECT ON mdsys.csw_harvestmetadata$ TO csw_usr_role;
GRANT SELECT ON mdsys.csw_plugin_map$ TO csw_usr_role;
GRANT SELECT ON mdsys.csw_record_types$ TO csw_usr_role;
GRANT SELECT ON mdsys.csw_recorddomainupdated$ TO csw_usr_role;
GRANT SELECT ON mdsys.csw_recordtablemdupdated$ TO csw_usr_role;
GRANT SELECT ON mdsys.csw_recordtableupdated$ TO csw_usr_role;
GRANT SELECT ON mdsys.csw_recordviewmap$ TO csw_usr_role;
GRANT SELECT ON mdsys.csw_rtxsdinfo$ TO csw_usr_role;
GRANT SELECT ON mdsys.csw_trg_table_temp$ TO csw_usr_role;
GRANT INSERT ON mdsys.csw_trg_table_temp$ TO csw_usr_role;
GRANT UPDATE ON mdsys.csw_trg_table_temp$ TO csw_usr_role;
GRANT DELETE ON mdsys.csw_trg_table_temp$ TO csw_usr_role;
GRANT DEBUG ON mdsys.csw_trg_table_temp$ TO csw_usr_role;
GRANT ALTER ON mdsys.csw_trg_table_temp$ TO csw_usr_role;
GRANT READ ON mdsys.csw_trg_table_temp$ TO csw_usr_role;
GRANT FLASHBACK ON mdsys.csw_trg_table_temp$ TO csw_usr_role;
GRANT QUERY REWRITE ON mdsys.csw_trg_table_temp$ TO csw_usr_role;
GRANT ON COMMIT REFRESH ON mdsys.csw_trg_table_temp$ TO csw_usr_role;
GRANT SELECT ON mdsys.ro_table TO csw_usr_role;