GRANT EXECUTE ON mdsys."/102ee2a8_PSSegmentSegType" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/106e9897_GeorGrayscaleEntry" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/10862847_Intersection" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/1138e59d_DBFReaderJGeomLogica" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/1145142e_LogicalNetLink" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/12163f96_NetworkIOImplPathEnt" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/1276ba31_LASImportExportLasAt" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/13578568_JRaster" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/13771389_LogicalSubNetworkImp" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/13b78f65_LogicalHeavyPath" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/13f03917_DummyLinkLevelSelect" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/143e7055_Buffer3" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/14d9fd6f_GeorFunctionalFittin" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/1504643_WKBWKBInputStream" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/15360697_GroupingLOD1Generali" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/153a39d1_BlobOutputStream" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/155fe610_ConstraintOperator" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/1691b4e5_SkipList" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/16e6a92f_nodeCostComparator" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/17a4a0a0_NetworkIOImplFeature" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/17c74781_LongLinkedHashMapEnt" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/17e4fe80_NetworkExplorer" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/185f9e5b_SdoGeometry" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/186942fa_NetworkIOImplOrdinat" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/188738d2_PartitionKmeans" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/19b62d25_DataException" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/19e939ae_TspAnalysisInfo" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/1a68c692_GeometryMetadata" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/1a763da9_GCPPoint" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/1a9fdeb9_TopoValidationExcept" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/1afbc6de_PCPyramidFilter1" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/1b8d2539_SpatialNetNode" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/1d3641da_NetworkCache" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/1e16d7bd_RasterInfoPyramidDes" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/1ee27fc7_SubLayerInfoGrayscal" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/1f9f80d1_DefaultLinkCostCalcu" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/1fd3523c_NetworkMetadata" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/1fd48eaf_SpatialSort1" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/1fd9e242_PriorityQueue" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/207ff2ab_PartitionPairMyInteg" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/20bab23_NetworkIOImplSubPathE" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/20c3d23b_NetworkDataException" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/20efaa47_JGeometryChainConver" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/2155856b_SubLayerInfoBinFunct" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/21904d45_FormatExpression" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/21f05637_ReverseGeocoder" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/222dd25c_DummyCostFunction" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/237fb2cb_YenDeviationComparab" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/240288a6_SpatialSort3" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/24d1e54f_SdoNumberArray" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/24fc3c97_DbConnection" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/252088c1_ElocationPartitionpa" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/2690c787_NetworkIOImplLinkInt" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/26baace1_SdoTglObjectArray" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/271750db_Logger" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/27dea35d_FeatureFilter" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/28753e7_GeorColormapEntry" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/29367bb1_YenDeviationShortest" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/2951989d_Prim" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/29ae3eca_NodeIdGoalNode" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/2b156297_FeaturePath" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/2b248550_TopoMapEdgeSplit" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/2b830f06_SpatialReferenceInfo" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/2b8a3e68_LRSGeometryG3D" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/2c53e844_SpatialSubNetworkImp" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/2c92c8c7_TreeNode" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/2cf0960_RTreeJoinRes" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/2e0eff76_CachedNetworkIOImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/2f847630_EuclideanCostFunctio" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/2f99fe21_AStar" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/2fa84dcd_LogicalPartitionImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/2ff82de1_JGeometryUtilityPoin" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/30559e24_SdoGeorPKG" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/32382c26_ElocationTruckData" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/324fdcae_TopoMapWrapper" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/32bdfa4_HttpClientGeocoder" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/334d6274_LBServer" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/33a29762_ElocationTruckDataTr" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/33b59d49_LogicalHeavyPathImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/3487aaca_ServerStatus" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/349c1dd2_NetworkAnalyst" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/34ce400f_LogicalNode" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/34cfa393_LinkLevelGoalNode" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/35f5e40f_WKInputStream" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/375c4ec3_RationalFunction" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/378df9a3_RasterInfoDimensionS" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/387504d3_NetworkMetadataImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/38c14947_SdoTopoObjectArray" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/39b18dc9_BlobCodec" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/3a1e3e42_LinkNotFoundExceptio" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/3a6ee40_NetworkAnalysisConfig" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/3acf2e07_JGeometryLineStringI" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/3ba629e3_LODConfigsxsd" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/3c770538_SpatialPartition" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/3c938260_NetworkAnalystSubPat" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/3d46f5be_VisitedNode" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/3d5d357e_TspOp2ComparablePoin" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/3db48bb6_ShortestPathAStar" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/3dba18d9_FeatureElementFeatur" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/3e326ab7_NetworkBuffer" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/3e44ae94_Abstract2DGeomCostFu" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/3e6e9106_FeatureDataImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/3e7fa114_SdoGeoRaster" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/3ed986d2_SegmentationDataType" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/3eff7056_LODAnalysisInfo" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/3f400f93_LogicalLightSubPath" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/3f4c5216_JDBCClassLoader10g" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/3f81fc50_TopoFrame1" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/3f95ece_NetworkSearchPartialL" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/402ee110_J3D_Geometry" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/4049c980_LogicalLightPath" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/407ee586_BufferChainSplitter" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/40e41e73_CountryProfile" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/410e4f84_SecureRandom" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/413f7686_NetworkManagerPathNo" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/41580df6_ElementExtractor" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/417e8ff6_JGeometryD3" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/418562f4_LongLinkedHashMap" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/41f51f3a_LongHashMap" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/4239cf98_GeorHistogramEntry" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/424037cf_SdoOrdinateArray" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/42c667ae_GeoRasterSRSAdapter" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/437f215_LASImportExport1" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/44046cb7_TspOp21" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/449c4960_Buffer4" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/45064d8e_PostalCode" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/4610425b_ChecksumHelperCEng" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/470e1c1c_PostalCodeCache" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/473717dc_SDODoubleGeneralPath" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/474c9b12_SdoPicklerUnpickleHe" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/48530578_KeywordTable" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/48a4e345_UserDataIO" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/4944b492_PSSegmentMonotoneUpd" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/4a558a5c_CachedNetworkIOWMImp" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/4b823849_UserDataImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/4d49133b_RTreeRTreePlot1" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/4d6360de_SubLayerInfoHistogra" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/4d90f23d_nodeDegreeComparator" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/4dc30889_TopoMapSmartPoint" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/4e155127_YenDeviation" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/4e42d840_SubLayerInfoCellPseu" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/4e723dfc_LogicalBasicNetworkI" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/4e9a2ee9_IdentifiablePriority" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/4eaaceb7_YenDeviationNodesToA" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/4f5fa759_JDBCAdapter" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/4fbf8997_RouterDataSource" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/503acd04_SdoTglObject" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/50611a80_TreeImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/508baebf_FeatureFilterOperato" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/512a8c65_SDODimArray" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/51fce785_SubLayerInfoScalingF" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/5244ab1d_PSSegment" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/52be9f77_AllShortestPaths" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/52edd1b_JDBCExtensionInterfac" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/534b8426_ShortestPath" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/540dac42_ElocationPartition" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/54298e57_LASImportExportLasHe" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/55089d18_JGeometry" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/5528869b_ShapefileHdr" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/554b5878_TimeZone" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/562bfaec_Dijkstra" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/56edd96a_LinkImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/570f41b4_NetworkSearchPointOn" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/5712ddae_AddressFormat" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/578c2b04_SubLayerInfoRasterGr" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/57f49f96_KShortestPaths" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/589849b7_LODUserDataIO" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/58cdebe3_NetworkManager" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/593e6d15_NetworkSearchNetwork" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/5997c708_SampleShapefileToJGe" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/5add49ef_GraphLayout" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/5bada5a2_AddressTokenizer" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/5bea5a9_ElocationTurnRestrict" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/5c00bb96_AdaptersPtclass" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/5c4567a1_SpatialLinkImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/5c855f6e_SpatialPartitionImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/5cd3f1c3_PartitionUpdate" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/5cde12ec_BreadthFirstSearch" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/5d6b400d_SpanningTree" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/5db0c8dc_DataSourceException" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/5e11f542_AStarSolution" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/5e4a85d3_LogicalPath" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/5e4bc1f5_ThinClientGeocoder" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/5e695b59_NetworkFactory" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/5ec10001_JPoint2DD" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/5f496d56_PartitionBlobTransla" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/60851191_RoutingEngineExcepti" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/60887f2d_SubLayerInfoRectangu" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/60e19c64_ChainCenterPoint" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/61709f5_Road" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/62079a0e_PrintUtilityComparab" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/62133b42_NetworkIOForInMemory" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/621866a9_RasterInfoBlockingDe" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/633055_LASImportExport" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/64b5baba_NetworkSearchNodeLin" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/65aab127_AdminArea" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/65ddae63_LogicalSubPathImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/6675f6df_NetworkSearch" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/66d4cbab_NetworkCache" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/687b57f1_PerformanceInfo" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/695cb036_ProfileValidatorExce" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/69dbd2cb_headhtml" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/6a0ed54e_LongLinkedHashMap2" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/6a4fffa1_JGeoRasterAdapter" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/6b8ab103_Compressor" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/6bd9035c_Buffer5" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/6c25142c_JGeometryElementIter" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/6ca24f_PrintUtility" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/6ce048bc_SeedGeneratorinvokeS" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/6de1c065_GoalNodeOperator" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/6e0dae03_NetworkSearchStatist" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/6e6e19d7_FeatureLayer" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/6e77c52_Generalization3D" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/6eb03abf_Sorter" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/6ec20d7b_LODGoalNode" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/6f1d3b57_GenericAddressParser" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/6f2679e3_WKTWKTInputStream" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/6fefa8e7_ElocationTurnRestric" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/70178183_SubLayerInfoCellCoun" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/70b1389e_LogicalLinkImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/70cd29df_DBFReaderJGeomCharac" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/714e65ed_LRUCachingHandler" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/72f777cf_SdoPickler" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/730286c8_FeatureData" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/731cb43e_IndexRecord" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/733ed0cf_SpatialSort" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/73580b35_LASImportExportLas10" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/7418e0aa_XMLUtility" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/7433516c_DummyNodeCostCalcula" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/745f90f4_LogicalSubNetwork" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/74fcd842_BandReferenceInfoBan" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/75199e43_PairwiseShortestPath" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/752e45dd_GeocoderConfig" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/760c03bc_DefaultPairwiseShort" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/761172aa_AddressParserConfig" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/7613f5f6_SeedGenerator" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/761d1783_LASImportExportLas12" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/764908cc_ShapefileReaderJGeom" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/7657e7a4_Polynomial" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/775db477_FeatureLayerMetadata" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/77b7a43d_IdentifiableBinaryHe" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/77cd6977_TopoMapAlongSegmentC" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/78331538_JGeometryPoint" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/783319fb_FormatTransformer" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/78fcde4a_GeoRasterImageNodata" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/7a1c4d6b_SpatialPath" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/7a490022_AnalysisInfo" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/7ac522c_PairwiseCostCalculato" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/7b586b00_BufferIntComp" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/7c917f61_TIFFWriter" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/7ccafd20_UserDataHolder" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/7d0414cb_JGeometryChainConver" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/7dc9ed4e_DBFReaderJGeomDateCo" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/7ed52a95_GCServer" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/7efa21f0_NetworkPartition" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/7f552369_TopoMapInt" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/7fae395f_RTreeRTreePlot" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/80916a82_UserDataEntry" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/815b6238_LODTimer" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/83882dc6_TreeLink" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/83a09182_Geocoder" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/83a9f125_SeedGeneratormyPA" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/83c29f4e_PartitionUtility" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/83d15702_ExtentType" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/843a9d92_SubLayerInfoColormap" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/84ac9a2b_LayerInfo" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/84b44aeb_PriorityQueue" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/8500ba6b_JPEGWriter" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/85a062fb_Road1" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/86528b85_HeavyPointOnNet" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/86847803_XMLHelper4Geocoder" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/86969fcb_MaxCostConstraint" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/86c36aed_AnalysisUtilityNodeC" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/86fa4112_LODUserDataIOSDO" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/876cf54_RTreeStackEntry" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/87a18a47_PathFeature" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/87b22765_LongHashMapEntry" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/888d4a0e_LogicalPartition" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/88bab003_ConvexHull" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/88d48070_TurnRestriction" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/89d5d9f9_NodeCosts" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/8a3c8c23_MinimumSpanningTree" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/8a524433_JDBCClassLoader" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/8a634753_TopoPreprocess" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/8b9c3a9d_NetworkIOImplUpdated" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/8c3e0d02_JGeometry2" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/8c463612_SampleShapefileToJGe" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/8c5d3f7d_GCServerGCStarter" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/8c61734c_SQLParserStub" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/8d8e28e5_MatchMode" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/8d9f6c2a_LogicalNetNodeImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/8e3f285e_SpatialHeavyPathImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/8e6eaf44_RTreeJoinEntry" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/8eab658c_CategorizedUserData" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/8eca5366_JGeometryGc_trans" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/8ffd9672_DBFReaderJGeomRecord" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/900ec01d_LongLinkedHashMap1" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/90254cc3_PerformanceMeasure" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/90530bd7_TspNearestNeighbor" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/906a57a7_GeorGtfParser" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/9071c2de_NetworkIOImplUpdated" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/90937f6d_PCPyramidFilterPoint" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/90d5b227_JGeometryDensifyData" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/90eca835_AStarNode" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/9126049_OrderedLongSet" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/918fe946_SubLayerInfoStatisti" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/91c0cefa_GoalNode" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/92404e07_QueryUtility" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/928b6b32_JRasterAdapter" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/9332bfa6_JGeometryLineStringI" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/93d2287f_BandReferenceInfo" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/948ebaac_CategorizedUserDataI" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/9490691d_SdoTopoObject" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/955700b8_LBSException" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/95c6e293_SpatialNetLinkImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/95d4ab06_PathFeatureImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/95e73e96_UserDataMetadataImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/95f4e7e9_LODConfigs11xsd" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/97121448_GenericGeocoder" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/976f73d9_PNGWriter" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/97736ae5_linkComparator" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/9899cade_JGeoRaster" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/98b1cf3a_Dijkstra" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/98c92075_AStarCostFunction" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/9944c11f_LogicalSubPath" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/9a7a58f9_JGeoRasterMeta" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/9b4d4bd2_SpatialPathImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/9b7be03d_NetworkIOImplBufferD" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/9b99493a_DistanceFunction" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/9c6e3ee5_CountryNameTable" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/9ccd36de_YenDeviationPathKey" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/9d227850_PrintUtilityComparab" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/9d27ee71_SpatialReferenceInfo" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/9d4abdc7_BlobDecodeParam" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/9d5990b6_OracleDataSourceHand" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/9e031425_DefaultPairwiseCostC" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/9e50d21e_NetworkSearchFeature" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/9ef8b76b_LogicalLightSubPathI" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/9f03ad4b_HouseNumberHelper" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/9f91ac17_GeocoderClient" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/9fad738_RTreeJoinEntryCmp" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/a05b6304_ChainAccurateSum" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/a10358eb_ElocationNode" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/a15ee7c4_TreeLinkImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/a1732598_RouterVersion" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/a179f687_CostNode" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/a2859fee_BreadthFirstSearchFI" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/a3155bbc_PCPyramidFilterChild" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/a31c0304_SpatialNetLink" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/a3e12f8a_JP2Compressor" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/a4684ceb_LODNetworkWrapper" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/a4e3ff65_StreetTypeFormat" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/a5d2e361_GeocoderConfigList" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/a605671f_DataSourceHandler" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/a68c88d8_ElocationTurnRestric" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/a6f4abff_InvalidTopoOperation" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/a7519cbb_DefaultNodeCostCalcu" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/a75a26f8_NodeNotFoundExceptio" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/a76d95b7_SdoElemInfoArray" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/a7719bd6_DepthFirstSearchLIFO" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/a7845786_SpatialReferenceInfo" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/a7a60acc_ExtendedKML2" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/a7b5d73e_SdoPointType" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/a8d0322d_PCPyramidFilter" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/a8d27e67_GeoRasterImageProces" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/a902d4d4_SpatialBasicNetworkI" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/a91d3aee_FeatureMetadata" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/a9dee1d6_GeorHistogram" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/aa16deae_CostDifference" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/aa6dac60_SdoEdgeArray" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/aa8c5690_TspPathFeature" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/ab2cb38f_LogicalPathImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/ab2ec3e0_AddressFormatProfile" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/ac0f7327_BlobImage" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/ac47972c_BinaryHeap" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/ac4b66e4_UserDataMetadata" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/ac5129e6_IdentifiableBinaryHe" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/acc26fb8_ChecksumHelper" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/accb27f0_JDBCAdapterDefaultJD" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/acd3c52f_NetworkBufferDoubleI" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/acd8f041_FeatureLayerMetadata" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/ad1a4a95_SpatialSubNetwork" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/ae5cbb17_SpatialBasicNetwork" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/af2b5ee0_NetworkAdapter" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/afbc1dbb_CachedNetworkIO" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/afbfad1c_NetworkAdapterSDO" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b02ca2fb_PathCost" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b088a6bb_DBFReaderJGeomNumeri" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b0bdf531_HilbertMBR" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b0bf4886_NetworkImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b0e2271_LeveledNetworkCache" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b118aca3_NetworkConstraint" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b155ffc8_GoalNodeOperatorComb" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b1a193de_NodeImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b24817c7_Buffer1" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b2a47a6f_SDODoubleGeneralPath" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b2a4dad7_SystemConstraint" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b33419d9_GeoRasterGeoTIFFInte" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b33c1d22_NetworkSearchMatched" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b3575e1a_CachingHandler" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b3c6713b_SpatialSubPathImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b431db67_LinkCostCalculator" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b46e0db3_GeorJP2Interface" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b46fe87c_FeatureFeatureType" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b4948fd6_BufferEvent" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b5434586_LRUCachingHandlerPar" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b54e1e2_MDPointImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b56145_CellCoordinateType" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b5956ed3_ResolutionType" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b59dc435_SdoGeorAggrPKG" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b5d1850_YenDeviation1" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b5d21daf_ListLengthComparator" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b6bd871a_LogicalNetLinkImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b71dcac6_SubLayerInfo" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b7328870_GeoTIFFWriter" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b74030a8_LODNetworkManager" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b745ab5_GML3GMLVersion" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b7cfe9a7_JGeometryUtility" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b83eb469_AddressParserPool" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b84d073_GeorColormap" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b8979f1b_SubPathImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b8f14222_NetworkUpdate" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b93a6787_TspNearestNeighbor1" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b93f9f08_NetworkIOImplSpatial" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/b9bface9_GCUtil" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/ba70dab1_ConnectionManager" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/bacffc91_ConstraintOperatorCo" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/bb0cf550_TurnRestrictionoutEd" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/bbe35112_AnalysisUtilityPoint" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/bbf6f125_MaxDepthConstraint" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/bc2a95db_GeocoderAddress" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/bc76ba38_PartitionMultilevel" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/bd0fa28_GeodeticCostFunction" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/be0f90fc_SdoGeorAdminPKG" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/be1433c1_UserData" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/be18f664_MethodNotSupportedEx" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/bec63728_GeoRasterImage" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/bef1b668_GeocoderException" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/bfb98d82_FlowNetwork" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/c0149231_NetworkBufferLinkInt" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/c0292315_GeocoderImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/c0849655_JGeometryGeomParser" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/c14b8ec7_CachedNetworkIOWM" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/c244cda8_AStarAStarVisitedNod" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/c25d65c9_SdoGeorUtlPKG" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/c29189ee_ScoreComparator" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/c2d627dc_AnalysisUtility" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/c2dbcdf4_FormatTransformerMet" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/c31ee94f_JP2Writer" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/c4450588_DBFReaderJGeom" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/c48c78e0_TopoMapPointStackEnt" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/c4cbdb8f_GraphTimer" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/c5ce9400_NetworkIOImplConfigP" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/c5e354f0_BufGeom" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/c625e569_LODConfig" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/c65534af_PartitionBlob" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/c6d1573f_IdentifiablePriority" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/c7118277_NetworkBufferElement" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/c840e66e_Buffer2" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/c8aeb20d_RasterInfoCompressio" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/c8dd9346_BinaryHeap" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/c950e35b_Region" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/c98484ac_NetworkIOImplRSMetaS" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/ca04008b_POI" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/ca24094e_RTreeMyPriorityQueue" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/ca33756_ByteOrderBigEndian" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/cabd8eb1_NDMStringID" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/cc3739ab_GeocoderAddress" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/cc927074_DynamicLinkLevelSele" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/cd38b02c_FeatureLayerImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/cda68f4f_PointOnNet" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/cdcd8202_TreeNodeImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/cdd52aef_NetworkIOConfig" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/cdd90161_SdoGeorRaPKG" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/cdf836cc_RasterInfo" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/ce3f022d_SISToIISAdapter" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/cf1bf9b5_HilbertBlockRecord" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/d014ac0d_LODNetworkConstraint" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/d0a59ae6_LogicalLightPathImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/d0ab1c33_TopoMapAlongEdgeComp" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/d1026c84_NetworkCacheItem" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/d12b8de1_SubLayerInfoNODATATy" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/d1f18a20_TopoDataException" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/d25a46f4_IOUtility" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/d3a0cd3d_FeatureElementImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/d4441974_WKBasisVectorOfInt" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/d4ccc124_HistoryMetadata" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/d600b96c_UserDataHolderImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/d6019381_NodeCostCalculator" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/d68945d8_LogicalNetNode" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/d6d3e921_SubLayerInfoRasterCo" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/d7397e4a_SpatialLink" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/d73e889f_SdoGeorPKGSdoGeorGCP" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/d779e532_SpatialSubPath" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/d7e8cb09_YenDeviationLinksToA" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/d8de0ff6_HilbertHilbertSelect" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/d912c7d8_DbDataSource" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/d92bb36d_FlowNode" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/d94f0d7c_BLOBWriter" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/da47053a_SpatialSort2" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/da5427d1_FeatureElement" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/daf03e4d_SpatialNetNodeImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/db1ca3e5_JGeometry4" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/dbb4d19d_Buffer6" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/dbbfb1e4_LongHashSet" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/dbcf5e9e_ElocationEdge" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/dbf8243f_ObjectInfo" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/dcaeccf3_PartitionManager" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/dcb9dbfc_nodeIncLnkCostCompar" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/dd01d4a0_RoadGrid" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/dd3de40_NetworkAnalyst1" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/dd4719bd_DBFieldDesc" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/dd66e536_TSPTourFlag" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/dde577b3_PathImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/ded640ab_SpatialHeavyPath" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/df256c69_GeometryExceptionWit" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/e05a9e5a_IntArrayList" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/e0a10783_ElocationTurnRestric" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/e0c95570_SdoTopoGeometry" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/e14704e9_TspPath" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/e17b32dd_LODConfigsxml" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/e1a6e33e_AnalysisUtilityDefau" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/e1a7b4b4_Feature" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/e1db3ea2_LODConfigException" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/e1fe6309_IDataSource" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/e240445a_BMPWriter" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/e34598e8_PartitionPair" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/e35ccf38_DepthFirstSearch" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/e3d84d9_HeuristicCostFunction" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/e3dda7ca_FeatureImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/e4034bd9_ByteOrderLittleEndia" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/e4bfb2c7_JGeometryLT_transfor" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/e4e2d7af_GeoRasterException" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/e5c5916b_AddressParser" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/e5decdeb_NetworkIOImpl1" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/e63e4323_RTreeTreeNode" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/e6ecb115_NetworkIO" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/e7730a7a_BufferEventType" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/e7ea0d67_PartitionBlobTransla" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/e7f37ac5_Settlement" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/e866f152_TspOp2" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/e8766d28_LinkLevelSelector" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/e87fe748_Municipality" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/e8d4327a_FeatureFilterOperato" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/e9008b6c_LongHashMap1" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/e9e822eb_JGeometryD2" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/ea21c709_SQLGeocoderStub" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/ea6b4fa7_CachingPolicy" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/ea762d56_ShapefileFeatureJGeo" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/eba1cb38_GRImageWriteParam" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/ec9f33aa_TemporalReferenceInf" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/eca87f72_GeorGrayscale" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/ed5bf8e1_StAXCityGML" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/ee8e1dfc_BlobImageDecoder" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/ef149653_LODNetworkException" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/eff083cb_SpatialNodeImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/f10c86eb_AnalysisInfoImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/f16e0def_CountryProfileList" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/f1892dbb_LogicalBasicNetwork" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/f26b1427_LogicalLink" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/f30c2424_LODNetworkFactory" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/f3abaa0f_NetworkUtility" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/f522e80_ConfigManager" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/f6668d77_JGeometry3" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/f6a0dbab_SpatialReferenceInfo" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/f6b7c18_WKBasisVectorOfDouble" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/f6c2be6c_SpatialNode" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/f6f51381_PartitionBlobTransla" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/f7c0e173_SubLayerInfoRasterPs" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/f854b341_ElocationTruckData1" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/f877485d_FlowLink" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/f8d99666_NDMTimer" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/f90975ef_XMLConfigurable" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/f9c4ebde_TspNearestNeighborFi" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/f9d2a0c_NetworkIOImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/fa500f4d_AdminAreaCache" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/faa5cf1f_TopoEntityNotFoundEx" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/facfc21e_SkipListData" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/fae2cb0b_GeocoderVersion" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/faf0f1af_JDBCAdapter1" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/fb2fabca_Buffer7" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/fb37c292_NetworkWrapper" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/fb7c5063_LinkCostFunction" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/fc0e658d_Matrix" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/fc14e333_GeoRasterAdapter" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/fc7881f7_SpatialReferenceInfo" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/fcf5a9d_AdapterShapefileJGeom" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/fd1e6ea_PCPyramidFilterBlock" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/fd247f09_SubLayerInfoCellGray" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/fd445bc3_RTreeComparatorImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/fd8823f1_DummyLinkCostCalcula" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/fedea84c_LogicalNodeImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/ff30f001_SdoGeorPKGSdoGeorGCP" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/ffa4f4ef_JGeometryLineStringI" TO "PUBLIC";
GRANT EXECUTE ON mdsys."/ffbd77e8_JGeometry1" TO "PUBLIC";
GRANT EXECUTE ON mdsys.aggrcentroid TO "PUBLIC";
GRANT EXECUTE ON mdsys.aggrconcat TO "PUBLIC";
GRANT EXECUTE ON mdsys.aggrconvexhull TO "PUBLIC";
GRANT EXECUTE ON mdsys.aggrlrsconcat TO "PUBLIC";
GRANT EXECUTE ON mdsys.aggrlrsconcat3d TO "PUBLIC";
GRANT EXECUTE ON mdsys.aggrmbr TO "PUBLIC";
GRANT EXECUTE ON mdsys.aggrunion TO "PUBLIC";
GRANT SELECT ON mdsys.all_annotation_text_metadata TO "PUBLIC";
GRANT SELECT ON mdsys.all_geometry_columns TO "PUBLIC";
GRANT SELECT ON mdsys.all_sdo_3dthemes TO "PUBLIC";
GRANT SELECT ON mdsys.all_sdo_3dtxfms TO "PUBLIC";
GRANT SELECT ON mdsys.all_sdo_animations TO "PUBLIC";
GRANT SELECT ON mdsys.all_sdo_cached_maps TO "PUBLIC";
GRANT SELECT ON mdsys.all_sdo_geom_metadata TO "PUBLIC";
GRANT SELECT ON mdsys.all_sdo_geor_sysdata TO "PUBLIC";
GRANT SELECT ON mdsys.all_sdo_index_info TO "PUBLIC";
GRANT SELECT ON mdsys.all_sdo_index_metadata TO "PUBLIC";
GRANT SELECT ON mdsys.all_sdo_lightsources TO "PUBLIC";
GRANT SELECT ON mdsys.all_sdo_lrs_metadata TO "PUBLIC";
GRANT SELECT ON mdsys.all_sdo_maps TO "PUBLIC";
GRANT SELECT ON mdsys.all_sdo_network_constraints TO "PUBLIC";
GRANT SELECT ON mdsys.all_sdo_network_feature TO "PUBLIC";
GRANT SELECT ON mdsys.all_sdo_network_histories TO "PUBLIC";
GRANT SELECT ON mdsys.all_sdo_network_java_objects TO "PUBLIC";
GRANT SELECT ON mdsys.all_sdo_network_locks_wm TO "PUBLIC";
GRANT SELECT ON mdsys.all_sdo_network_metadata TO "PUBLIC";
GRANT SELECT ON mdsys.all_sdo_network_timestamps TO "PUBLIC";
GRANT SELECT ON mdsys.all_sdo_network_user_data TO "PUBLIC";
GRANT SELECT ON mdsys.all_sdo_scenes TO "PUBLIC";
GRANT SELECT ON mdsys.all_sdo_styles TO "PUBLIC";
GRANT SELECT ON mdsys.all_sdo_themes TO "PUBLIC";
GRANT SELECT ON mdsys.all_sdo_tin_pc_sysdata TO "PUBLIC";
GRANT SELECT ON mdsys.all_sdo_topo_info TO "PUBLIC";
GRANT SELECT ON mdsys.all_sdo_topo_metadata TO "PUBLIC" WITH GRANT OPTION;
GRANT SELECT ON mdsys.all_sdo_viewframes TO "PUBLIC";
GRANT EXECUTE ON mdsys."Coordinate586_COLL" TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys."CoordinatesType585_T" TO "PUBLIC" WITH GRANT OPTION;
GRANT SELECT ON mdsys.cs_srs TO "PUBLIC";
GRANT SELECT ON mdsys.dba_sdo_maps TO "PUBLIC";
GRANT SELECT ON mdsys.dba_sdo_styles TO "PUBLIC";
GRANT SELECT ON mdsys.dba_sdo_themes TO "PUBLIC";
GRANT EXECUTE ON mdsys.elocation_edge_link_level TO "PUBLIC";
GRANT EXECUTE ON mdsys.epsg_param TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.epsg_params TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.f81_index_obj_array TO "PUBLIC";
GRANT EXECUTE ON mdsys.f81_index_object TO "PUBLIC";
GRANT EXECUTE ON mdsys.f81_nt_ind_type TO "PUBLIC";
GRANT SELECT ON mdsys.geodetic_srids TO "PUBLIC";
GRANT EXECUTE ON mdsys."Grid597_T" TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys."Grid600_COLL" TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys."GridApplication592_COLL" TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys."GridApplicationsType590_T" TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys."GridApplicationType591_T" TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys."GridDataType582_T" TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys."GridFile601_T" TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys."GridFileType598_T" TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys."GridLineType583_T" TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys."GridNode587_COLL" TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys."GridNodeType584_T" TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys."GridPropertiesType593_T" TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys."GridRow588_COLL" TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys."Grids599_T" TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys."GridType594_T" TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.h81_index_obj_array TO "PUBLIC";
GRANT EXECUTE ON mdsys.h81_index_object TO "PUBLIC";
GRANT EXECUTE ON mdsys.h81_nt_ind_type TO "PUBLIC";
GRANT EXECUTE ON mdsys.hhcellbndry TO "PUBLIC";
GRANT EXECUTE ON mdsys.hhencode_bylevel TO "PUBLIC";
GRANT EXECUTE ON mdsys.hhlength TO "PUBLIC";
GRANT EXECUTE ON mdsys.hhmatch TO "PUBLIC";
GRANT EXECUTE ON mdsys.hhmaxcode TO "PUBLIC";
GRANT EXECUTE ON mdsys.hhsubstr TO "PUBLIC";
GRANT EXECUTE ON mdsys."HierarchyParticipation595_T" TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.locator_within_distance TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.mbrcoordlist TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.mderr TO "PUBLIC";
GRANT EXECUTE ON mdsys.mdprvt_feature TO "PUBLIC";
GRANT EXECUTE ON mdsys.mdprvt_srid TO "PUBLIC";
GRANT SELECT ON mdsys.my_sdo_index_metadata TO "PUBLIC";
GRANT EXECUTE ON mdsys.ndm_vector_2d TO "PUBLIC";
GRANT SELECT ON mdsys.ntv2_xml_data TO "PUBLIC";
GRANT EXECUTE ON mdsys.num_array TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_area TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_asbinary TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_astext TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_boundary TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_buffer TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_centroid TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_contains TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_convexhull TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_cross TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_difference TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_dimension TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_disjoint TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_distance TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_endpoint TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_envelope TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_equals TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_exteriorring TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_geometryn TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_geometrytype TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_interiorringn TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_intersection TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_intersects TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_isclosed TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_isempty TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_isring TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_issimple TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_length TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_linestringfromtext TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_linestringfromwkb TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_multilinestringfromtext TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_multilinestringfromwkb TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_multipolygonfromtext TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_multipolygonfromwkb TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_numgeometries TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_numinteriorrings TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_numpoints TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_overlap TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_pointfromtext TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_pointfromwkb TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_pointn TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_pointonsurface TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_polygonfromtext TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_polygonfromwkb TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_relate TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_srid TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_startpoint TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_symmetricdifference TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_touch TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_union TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_within TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_x TO "PUBLIC";
GRANT EXECUTE ON mdsys.ogc_y TO "PUBLIC";
GRANT SELECT ON mdsys.ogis_geometry_columns TO "PUBLIC";
GRANT INSERT ON mdsys.ogis_geometry_columns TO "PUBLIC";
GRANT DELETE ON mdsys.ogis_geometry_columns TO "PUBLIC";
GRANT SELECT ON mdsys.ogis_spatial_reference_systems TO "PUBLIC";
GRANT INSERT ON mdsys.ogis_spatial_reference_systems TO "PUBLIC";
GRANT DELETE ON mdsys.ogis_spatial_reference_systems TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/geometry/Buffer" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/geometry/Chain" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/network/AStar" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/network/Bfs" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/network/Cache" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/network/Dfs" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/network/KDTree" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/network/KMeans" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/network/Kruskal" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/network/Link" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/network/lod/TSP" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/network/MBR" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/network/MBRImpl" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/network/MDPoint" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/network/NetNode" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/network/Network" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/network/Node" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/network/OraTst" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/network/Path" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/network/SubPath" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/network/Tree" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/network/TspPath" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/security/OHSH" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/security/ORC" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/topo/CompGeom" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/topo/Edge" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/topo/Face" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/topo/Node" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/topo/Point2DD" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/topo/TopoFrame" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/topo/TopoMap" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/util/Adapters" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/util/ByteOrder" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/util/DBFileHdr" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/util/DBMS" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/util/GML" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/util/GML2" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/util/GML3" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/util/GML3$1" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/util/GML3g" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/util/Hilbert" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/util/JDBCUtil" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/util/KML" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/util/KML2" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/util/Las2SqlLdr" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/util/Logger" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/util/RTree" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/util/RTree$Int" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/util/RTree$Span" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/util/StAXGML" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/util/Util" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/util/WKAdapter" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/util/WKB" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/util/WKBasis" TO "PUBLIC";
GRANT EXECUTE ON mdsys."oracle/spatial/util/WKT" TO "PUBLIC";
GRANT EXECUTE ON mdsys."Parent596_COLL" TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys."ParentType589_T" TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.prvt_idx TO "PUBLIC";
GRANT EXECUTE ON mdsys.qry2opt TO "PUBLIC";
GRANT EXECUTE ON mdsys.rowpointerlist TO "PUBLIC";
GRANT EXECUTE ON mdsys.rtree_filter TO "PUBLIC";
GRANT EXECUTE ON mdsys.rtree_nn TO "PUBLIC";
GRANT EXECUTE ON mdsys.rtreejoinfunc TO "PUBLIC";
GRANT SELECT ON mdsys.sample_seq TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_addr_array TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_admin TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_aggr TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_aggr_centroid TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_aggr_concat_lines TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_aggr_convexhull TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_aggr_lrs_concat TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_aggr_lrs_concat_3d TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_aggr_mbr TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_aggr_set_union TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_aggr_union TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_angle_units TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_anyinteract TO "PUBLIC" WITH GRANT OPTION;
GRANT SELECT ON mdsys.sdo_area_units TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_available_elem_ops TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_available_non_elem_ops TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_available_ops TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_catalog TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_contains TO "PUBLIC" WITH GRANT OPTION;
GRANT SELECT ON mdsys.sdo_coord_axes TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_coord_axis_names TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_coord_op_methods TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_coord_op_param_use TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_coord_op_param_vals TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_coord_op_params TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_coord_op_paths TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_coord_ops TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_coord_ref_sys TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_coord_ref_system TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_coord_sys TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_coveredby TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_covers TO "PUBLIC" WITH GRANT OPTION;
GRANT SELECT ON mdsys.sdo_crs_compound TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_crs_engineering TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_crs_geocentric TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_crs_geographic_plus_height TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_crs_geographic2d TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_crs_geographic3d TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_crs_projected TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_crs_vertical TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_cs TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_cs_context_information TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_cs_srs TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_csw_process TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_datum_engineering TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_datum_geodetic TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_datum_vertical TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_datums TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_datums_old_format TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_datums_old_snapshot TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_dim_array TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_dim_element TO "PUBLIC" WITH GRANT OPTION;
GRANT SELECT ON mdsys.sdo_dist_units TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_edge_array TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_elem_info_array TO "PUBLIC" WITH GRANT OPTION;
GRANT SELECT ON mdsys.sdo_ellipsoids TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_ellipsoids_old_format TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_ellipsoids_old_snapshot TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_equal TO "PUBLIC" WITH GRANT OPTION;
GRANT SELECT ON mdsys.sdo_feature_usage TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_filter TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_gcdr TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_geo_addr TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_geom TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_geom_path_elem TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_geom_path_info TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_geom_path_info_elem TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_geom_path_info_list TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_geometry TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_geometry_array TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_geor TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_geor_admin TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_geor_aggr TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_geor_aux TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_geor_colormap TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_geor_gcp TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_geor_gcp_collection TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_geor_gcpgeoreftype TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_geor_grayscale TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_geor_histogram TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_geor_metadata TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_geor_mosaic_0 TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_geor_mosaic_tab0 TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_geor_plugin_registry TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_geor_ra TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_geor_seq TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_geor_srs TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_geor_utl TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_geor_xmlschema_table TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_georaster TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_georaster_array TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_get_ityp_name TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_get_tab_part TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_gr_mosaic_0 TO "PUBLIC";
GRANT INSERT ON mdsys.sdo_gr_mosaic_0 TO "PUBLIC";
GRANT UPDATE ON mdsys.sdo_gr_mosaic_0 TO "PUBLIC";
GRANT DELETE ON mdsys.sdo_gr_mosaic_0 TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_gr_mosaic_1 TO "PUBLIC";
GRANT INSERT ON mdsys.sdo_gr_mosaic_1 TO "PUBLIC";
GRANT UPDATE ON mdsys.sdo_gr_mosaic_1 TO "PUBLIC";
GRANT DELETE ON mdsys.sdo_gr_mosaic_1 TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_gr_mosaic_2 TO "PUBLIC";
GRANT INSERT ON mdsys.sdo_gr_mosaic_2 TO "PUBLIC";
GRANT UPDATE ON mdsys.sdo_gr_mosaic_2 TO "PUBLIC";
GRANT DELETE ON mdsys.sdo_gr_mosaic_2 TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_gr_mosaic_3 TO "PUBLIC";
GRANT INSERT ON mdsys.sdo_gr_mosaic_3 TO "PUBLIC";
GRANT UPDATE ON mdsys.sdo_gr_mosaic_3 TO "PUBLIC";
GRANT DELETE ON mdsys.sdo_gr_mosaic_3 TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_gr_parallel TO "PUBLIC";
GRANT INSERT ON mdsys.sdo_gr_parallel TO "PUBLIC";
GRANT UPDATE ON mdsys.sdo_gr_parallel TO "PUBLIC";
GRANT DELETE ON mdsys.sdo_gr_parallel TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_gr_rdt_1 TO "PUBLIC";
GRANT INSERT ON mdsys.sdo_gr_rdt_1 TO "PUBLIC";
GRANT UPDATE ON mdsys.sdo_gr_rdt_1 TO "PUBLIC";
GRANT DELETE ON mdsys.sdo_gr_rdt_1 TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_gr_rdt_2 TO "PUBLIC";
GRANT INSERT ON mdsys.sdo_gr_rdt_2 TO "PUBLIC";
GRANT UPDATE ON mdsys.sdo_gr_rdt_2 TO "PUBLIC";
GRANT DELETE ON mdsys.sdo_gr_rdt_2 TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_idx TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_idx_tab_sequence TO "PUBLIC";
GRANT ALTER ON mdsys.sdo_idx_tab_sequence TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_inside TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_int_filter TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_int_relate TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_int2_filter TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_int2_relate TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_join TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_keywordarray TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_link_t TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_list_type TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_lrs TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_mbr TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_meta TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_migrate TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_ndm_id_seq TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_net TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_net_feat_elem TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_net_feat_elem_array TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_net_layer_feat TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_net_layer_feat_array TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_net_link TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_net_link_ntbl TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_net_mem TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_net_op TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_net_op_ntbl TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_net_partition TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_net_upd_hist TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_net_upd_hist_n TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_net_upd_hist_ntbl TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_net_upd_hist_tbl TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_network_manager_t TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_network_t TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_nn TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_nn_distance TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_node_t TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_number_array TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_numtab TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_ols TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_ols_directory TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_ols_locutl TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_ols_presentation TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_ols_route TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_on TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_ordinate_array TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_orgscl_type TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_overlapbdydisjoint TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_overlapbdyintersect TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_overlaps TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_owm_installed TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_path_t TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_pc TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_pc_blk TO "PUBLIC" WITH GRANT OPTION;
GRANT SELECT ON mdsys.sdo_pc_blk_table TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_pc_blk_type TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_pc_pkg TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_point_type TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_pointinpolygon TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_pqry TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_preferred_ops_system TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_preferred_ops_user TO "PUBLIC";
GRANT INSERT ON mdsys.sdo_preferred_ops_user TO "PUBLIC";
GRANT UPDATE ON mdsys.sdo_preferred_ops_user TO "PUBLIC";
GRANT DELETE ON mdsys.sdo_preferred_ops_user TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_pridx TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_prime_meridians TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_projections_old_format TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_projections_old_snapshot TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_range TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_range_array TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_raster TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_rasterset TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_regaggr TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_regaggrset TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_region TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_regionset TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_relate TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_relate_mask TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_relatemask_table TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_router_partition TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_rowidpair TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_rowidset TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_rtree_admin TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_rtree_filter TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_rtree_relate TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_sam TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_simple_filter TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_smpl_geometry TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_srid_chain TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_srid_list TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_st_tolerance TO "PUBLIC";
GRANT INSERT ON mdsys.sdo_st_tolerance TO "PUBLIC";
GRANT DELETE ON mdsys.sdo_st_tolerance TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_stat TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_stattab TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_string_array TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_string2_array TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_string2_arrayset TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_tfm_chain TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_tgl_object TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_tgl_object_array TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_tin TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_tin_blk TO "PUBLIC" WITH GRANT OPTION;
GRANT SELECT ON mdsys.sdo_tin_blk_table TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_tin_blk_type TO "PUBLIC" WITH GRANT OPTION;
GRANT SELECT ON mdsys.sdo_tin_pc_seq TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_tin_pc_sysdata_table TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_tin_pkg TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_topo TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_topo_data$ TO "PUBLIC";
GRANT INSERT ON mdsys.sdo_topo_data$ TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_topo_geometry TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_topo_geometry_layer TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_topo_geometry_layer_array TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_topo_geometry_layer_table TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_topo_map TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_topo_metadata TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_topo_nstd_tbl TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_topo_object TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_topo_object_array TO "PUBLIC" WITH GRANT OPTION;
GRANT SELECT ON mdsys.sdo_topo_relation_data TO "PUBLIC";
GRANT INSERT ON mdsys.sdo_topo_relation_data TO "PUBLIC";
GRANT DELETE ON mdsys.sdo_topo_relation_data TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_topo_transact_data TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_topo_transact_data$ TO "PUBLIC";
GRANT INSERT ON mdsys.sdo_topo_transact_data$ TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_touch TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdo_transient_rule TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_transient_rule_set TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_tune TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_txn_idx_deletes TO "PUBLIC";
GRANT INSERT ON mdsys.sdo_txn_idx_deletes TO "PUBLIC";
GRANT DELETE ON mdsys.sdo_txn_idx_deletes TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_txn_idx_exp_upd_rgn TO "PUBLIC";
GRANT INSERT ON mdsys.sdo_txn_idx_exp_upd_rgn TO "PUBLIC";
GRANT UPDATE ON mdsys.sdo_txn_idx_exp_upd_rgn TO "PUBLIC";
GRANT DELETE ON mdsys.sdo_txn_idx_exp_upd_rgn TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_txn_idx_inserts TO "PUBLIC";
GRANT INSERT ON mdsys.sdo_txn_idx_inserts TO "PUBLIC";
GRANT UPDATE ON mdsys.sdo_txn_idx_inserts TO "PUBLIC";
GRANT DELETE ON mdsys.sdo_txn_idx_inserts TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_units_of_measure TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_util TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_version TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_vpoint_type TO "PUBLIC" WITH GRANT OPTION;
GRANT SELECT ON mdsys.sdo_wfs_local_txns TO "PUBLIC";
GRANT INSERT ON mdsys.sdo_wfs_local_txns TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_wfs_lock TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_wfs_lock_util TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_wfs_process TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_within_distance TO "PUBLIC" WITH GRANT OPTION;
GRANT SELECT ON mdsys.sdo_ws_conference TO "PUBLIC";
GRANT INSERT ON mdsys.sdo_ws_conference TO "PUBLIC";
GRANT UPDATE ON mdsys.sdo_ws_conference TO "PUBLIC";
GRANT DELETE ON mdsys.sdo_ws_conference TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_ws_conference_ids TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_ws_conference_participants TO "PUBLIC";
GRANT INSERT ON mdsys.sdo_ws_conference_participants TO "PUBLIC";
GRANT UPDATE ON mdsys.sdo_ws_conference_participants TO "PUBLIC";
GRANT DELETE ON mdsys.sdo_ws_conference_participants TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_ws_conference_results TO "PUBLIC";
GRANT INSERT ON mdsys.sdo_ws_conference_results TO "PUBLIC";
GRANT UPDATE ON mdsys.sdo_ws_conference_results TO "PUBLIC";
GRANT DELETE ON mdsys.sdo_ws_conference_results TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdo_ws_process TO "PUBLIC";
GRANT SELECT ON mdsys.sdo_xml_schemas TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdoaggr TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdoaggrtype TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdocurpkg TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdonumlist TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdoridlist TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdoridtab TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.sdoridtable TO "PUBLIC";
GRANT EXECUTE ON mdsys.sdotnpc TO "PUBLIC";
GRANT EXECUTE ON mdsys.spatial_index TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.spclusters TO "PUBLIC";
GRANT SELECT ON mdsys.srsnamespace_table TO "PUBLIC";
GRANT INSERT ON mdsys.srsnamespace_table TO "PUBLIC";
GRANT DELETE ON mdsys.srsnamespace_table TO "PUBLIC";
GRANT EXECUTE ON mdsys.st_annot_textelement_array TO "PUBLIC";
GRANT EXECUTE ON mdsys.st_annotation_text TO "PUBLIC";
GRANT EXECUTE ON mdsys.st_annotationtextelement TO "PUBLIC";
GRANT EXECUTE ON mdsys.st_annotationtextelement_array TO "PUBLIC";
GRANT EXECUTE ON mdsys.st_circularstring TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.st_compoundcurve TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.st_curve TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.st_curve_array TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.st_curvepolygon TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.st_double_precision_array TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.st_geomcollection TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.st_geometry TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.st_geometry_array TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.st_linestring TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.st_linestring_array TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.st_multicurve TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.st_multilinestring TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.st_multipoint TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.st_multipolygon TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.st_multisurface TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.st_point TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.st_point_array TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.st_polygon TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.st_polygon_array TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.st_surface TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.st_surface_array TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.string_array TO "PUBLIC";
GRANT EXECUTE ON mdsys.stringlist TO "PUBLIC";
GRANT EXECUTE ON mdsys.stringlistlist TO "PUBLIC";
GRANT EXECUTE ON mdsys.tfm_plan TO "PUBLIC" WITH GRANT OPTION;
GRANT SELECT ON mdsys.tmp_coord_ops TO "PUBLIC" WITH GRANT OPTION;
GRANT EXECUTE ON mdsys.transform_map TO "PUBLIC";
GRANT EXECUTE ON mdsys."UnitOfMeasureType581_T" TO "PUBLIC" WITH GRANT OPTION;
GRANT SELECT ON mdsys.user_annotation_text_metadata TO "PUBLIC";
GRANT INSERT ON mdsys.user_annotation_text_metadata TO "PUBLIC";
GRANT UPDATE ON mdsys.user_annotation_text_metadata TO "PUBLIC";
GRANT DELETE ON mdsys.user_annotation_text_metadata TO "PUBLIC";
GRANT SELECT ON mdsys.user_geometry_columns TO "PUBLIC";
GRANT SELECT ON mdsys.user_sdo_3dthemes TO "PUBLIC";
GRANT INSERT ON mdsys.user_sdo_3dthemes TO "PUBLIC";
GRANT UPDATE ON mdsys.user_sdo_3dthemes TO "PUBLIC";
GRANT DELETE ON mdsys.user_sdo_3dthemes TO "PUBLIC";
GRANT SELECT ON mdsys.user_sdo_3dtxfms TO "PUBLIC";
GRANT INSERT ON mdsys.user_sdo_3dtxfms TO "PUBLIC";
GRANT UPDATE ON mdsys.user_sdo_3dtxfms TO "PUBLIC";
GRANT DELETE ON mdsys.user_sdo_3dtxfms TO "PUBLIC";
GRANT SELECT ON mdsys.user_sdo_animations TO "PUBLIC";
GRANT INSERT ON mdsys.user_sdo_animations TO "PUBLIC";
GRANT UPDATE ON mdsys.user_sdo_animations TO "PUBLIC";
GRANT DELETE ON mdsys.user_sdo_animations TO "PUBLIC";
GRANT SELECT ON mdsys.user_sdo_cached_maps TO "PUBLIC";
GRANT INSERT ON mdsys.user_sdo_cached_maps TO "PUBLIC";
GRANT UPDATE ON mdsys.user_sdo_cached_maps TO "PUBLIC";
GRANT DELETE ON mdsys.user_sdo_cached_maps TO "PUBLIC";
GRANT SELECT ON mdsys.user_sdo_geom_metadata TO "PUBLIC";
GRANT INSERT ON mdsys.user_sdo_geom_metadata TO "PUBLIC";
GRANT UPDATE ON mdsys.user_sdo_geom_metadata TO "PUBLIC";
GRANT DELETE ON mdsys.user_sdo_geom_metadata TO "PUBLIC";
GRANT SELECT ON mdsys.user_sdo_geor_sysdata TO "PUBLIC";
GRANT INSERT ON mdsys.user_sdo_geor_sysdata TO "PUBLIC";
GRANT UPDATE ON mdsys.user_sdo_geor_sysdata TO "PUBLIC";
GRANT DELETE ON mdsys.user_sdo_geor_sysdata TO "PUBLIC";
GRANT SELECT ON mdsys.user_sdo_index_info TO "PUBLIC";
GRANT SELECT ON mdsys.user_sdo_index_metadata TO "PUBLIC";
GRANT SELECT ON mdsys.user_sdo_lightsources TO "PUBLIC";
GRANT INSERT ON mdsys.user_sdo_lightsources TO "PUBLIC";
GRANT UPDATE ON mdsys.user_sdo_lightsources TO "PUBLIC";
GRANT DELETE ON mdsys.user_sdo_lightsources TO "PUBLIC";
GRANT SELECT ON mdsys.user_sdo_lrs_metadata TO "PUBLIC";
GRANT INSERT ON mdsys.user_sdo_lrs_metadata TO "PUBLIC";
GRANT UPDATE ON mdsys.user_sdo_lrs_metadata TO "PUBLIC";
GRANT DELETE ON mdsys.user_sdo_lrs_metadata TO "PUBLIC";
GRANT SELECT ON mdsys.user_sdo_maps TO "PUBLIC";
GRANT INSERT ON mdsys.user_sdo_maps TO "PUBLIC";
GRANT UPDATE ON mdsys.user_sdo_maps TO "PUBLIC";
GRANT DELETE ON mdsys.user_sdo_maps TO "PUBLIC";
GRANT SELECT ON mdsys.user_sdo_network_constraints TO "PUBLIC";
GRANT INSERT ON mdsys.user_sdo_network_constraints TO "PUBLIC";
GRANT UPDATE ON mdsys.user_sdo_network_constraints TO "PUBLIC";
GRANT DELETE ON mdsys.user_sdo_network_constraints TO "PUBLIC";
GRANT SELECT ON mdsys.user_sdo_network_feature TO "PUBLIC";
GRANT INSERT ON mdsys.user_sdo_network_feature TO "PUBLIC";
GRANT UPDATE ON mdsys.user_sdo_network_feature TO "PUBLIC";
GRANT DELETE ON mdsys.user_sdo_network_feature TO "PUBLIC";
GRANT SELECT ON mdsys.user_sdo_network_histories TO "PUBLIC";
GRANT INSERT ON mdsys.user_sdo_network_histories TO "PUBLIC";
GRANT UPDATE ON mdsys.user_sdo_network_histories TO "PUBLIC";
GRANT DELETE ON mdsys.user_sdo_network_histories TO "PUBLIC";
GRANT SELECT ON mdsys.user_sdo_network_java_objects TO "PUBLIC";
GRANT INSERT ON mdsys.user_sdo_network_java_objects TO "PUBLIC";
GRANT UPDATE ON mdsys.user_sdo_network_java_objects TO "PUBLIC";
GRANT DELETE ON mdsys.user_sdo_network_java_objects TO "PUBLIC";
GRANT SELECT ON mdsys.user_sdo_network_locks_wm TO "PUBLIC";
GRANT INSERT ON mdsys.user_sdo_network_locks_wm TO "PUBLIC";
GRANT UPDATE ON mdsys.user_sdo_network_locks_wm TO "PUBLIC";
GRANT DELETE ON mdsys.user_sdo_network_locks_wm TO "PUBLIC";
GRANT SELECT ON mdsys.user_sdo_network_metadata TO "PUBLIC";
GRANT INSERT ON mdsys.user_sdo_network_metadata TO "PUBLIC";
GRANT UPDATE ON mdsys.user_sdo_network_metadata TO "PUBLIC";
GRANT DELETE ON mdsys.user_sdo_network_metadata TO "PUBLIC";
GRANT SELECT ON mdsys.user_sdo_network_timestamps TO "PUBLIC";
GRANT INSERT ON mdsys.user_sdo_network_timestamps TO "PUBLIC";
GRANT UPDATE ON mdsys.user_sdo_network_timestamps TO "PUBLIC";
GRANT DELETE ON mdsys.user_sdo_network_timestamps TO "PUBLIC";
GRANT SELECT ON mdsys.user_sdo_network_user_data TO "PUBLIC";
GRANT INSERT ON mdsys.user_sdo_network_user_data TO "PUBLIC";
GRANT UPDATE ON mdsys.user_sdo_network_user_data TO "PUBLIC";
GRANT DELETE ON mdsys.user_sdo_network_user_data TO "PUBLIC";
GRANT SELECT ON mdsys.user_sdo_scenes TO "PUBLIC";
GRANT INSERT ON mdsys.user_sdo_scenes TO "PUBLIC";
GRANT UPDATE ON mdsys.user_sdo_scenes TO "PUBLIC";
GRANT DELETE ON mdsys.user_sdo_scenes TO "PUBLIC";
GRANT SELECT ON mdsys.user_sdo_styles TO "PUBLIC";
GRANT INSERT ON mdsys.user_sdo_styles TO "PUBLIC";
GRANT UPDATE ON mdsys.user_sdo_styles TO "PUBLIC";
GRANT DELETE ON mdsys.user_sdo_styles TO "PUBLIC";
GRANT SELECT ON mdsys.user_sdo_themes TO "PUBLIC";
GRANT INSERT ON mdsys.user_sdo_themes TO "PUBLIC";
GRANT UPDATE ON mdsys.user_sdo_themes TO "PUBLIC";
GRANT DELETE ON mdsys.user_sdo_themes TO "PUBLIC";
GRANT SELECT ON mdsys.user_sdo_tin_pc_sysdata TO "PUBLIC";
GRANT SELECT ON mdsys.user_sdo_topo_info TO "PUBLIC";
GRANT SELECT ON mdsys.user_sdo_topo_metadata TO "PUBLIC" WITH GRANT OPTION;
GRANT SELECT ON mdsys.user_sdo_viewframes TO "PUBLIC";
GRANT INSERT ON mdsys.user_sdo_viewframes TO "PUBLIC";
GRANT UPDATE ON mdsys.user_sdo_viewframes TO "PUBLIC";
GRANT DELETE ON mdsys.user_sdo_viewframes TO "PUBLIC";
GRANT EXECUTE ON mdsys.v81_index_obj_array TO "PUBLIC";
GRANT EXECUTE ON mdsys.v81_index_object TO "PUBLIC";
GRANT EXECUTE ON mdsys.v81_nt_ind_type TO "PUBLIC";
GRANT EXECUTE ON mdsys.vector_2d TO "PUBLIC";
GRANT EXECUTE ON mdsys.vertex_set_type TO "PUBLIC";
GRANT EXECUTE ON mdsys.vertex_type TO "PUBLIC";
GRANT EXECUTE ON mdsys.wfscomplextype TO "PUBLIC";