GRANT SELECT ON mdsys.currentsessiontokenmap$ TO spatial_wfs_admin_usr;
GRANT INSERT ON mdsys.currentsessiontokenmap$ TO spatial_wfs_admin_usr;
GRANT UPDATE ON mdsys.currentsessiontokenmap$ TO spatial_wfs_admin_usr;
GRANT DELETE ON mdsys.currentsessiontokenmap$ TO spatial_wfs_admin_usr;
GRANT DEBUG ON mdsys.currentsessiontokenmap$ TO spatial_wfs_admin_usr;
GRANT REFERENCES ON mdsys.currentsessiontokenmap$ TO spatial_wfs_admin_usr;
GRANT READ ON mdsys.currentsessiontokenmap$ TO spatial_wfs_admin_usr;
GRANT FLASHBACK ON mdsys.currentsessiontokenmap$ TO spatial_wfs_admin_usr;
GRANT QUERY REWRITE ON mdsys.currentsessiontokenmap$ TO spatial_wfs_admin_usr;
GRANT ON COMMIT REFRESH ON mdsys.currentsessiontokenmap$ TO spatial_wfs_admin_usr;
GRANT MERGE VIEW ON mdsys.currentsessiontokenmap$ TO spatial_wfs_admin_usr;
GRANT SELECT ON mdsys.currentsessiontokenmap_t$ TO spatial_wfs_admin_usr;
GRANT INSERT ON mdsys.currentsessiontokenmap_t$ TO spatial_wfs_admin_usr;
GRANT UPDATE ON mdsys.currentsessiontokenmap_t$ TO spatial_wfs_admin_usr;
GRANT DELETE ON mdsys.currentsessiontokenmap_t$ TO spatial_wfs_admin_usr;
GRANT DEBUG ON mdsys.currentsessiontokenmap_t$ TO spatial_wfs_admin_usr;
GRANT REFERENCES ON mdsys.currentsessiontokenmap_t$ TO spatial_wfs_admin_usr;
GRANT ALTER ON mdsys.currentsessiontokenmap_t$ TO spatial_wfs_admin_usr;
GRANT INDEX ON mdsys.currentsessiontokenmap_t$ TO spatial_wfs_admin_usr;
GRANT READ ON mdsys.currentsessiontokenmap_t$ TO spatial_wfs_admin_usr;
GRANT FLASHBACK ON mdsys.currentsessiontokenmap_t$ TO spatial_wfs_admin_usr;
GRANT QUERY REWRITE ON mdsys.currentsessiontokenmap_t$ TO spatial_wfs_admin_usr;
GRANT ON COMMIT REFRESH ON mdsys.currentsessiontokenmap_t$ TO spatial_wfs_admin_usr;
GRANT SELECT ON mdsys.ft_sq$ TO spatial_wfs_admin_usr;
GRANT ALTER ON mdsys.ft_sq$ TO spatial_wfs_admin_usr;
GRANT SELECT ON mdsys.r_table TO spatial_wfs_admin_usr;
GRANT INSERT ON mdsys.r_table TO spatial_wfs_admin_usr;
GRANT UPDATE ON mdsys.r_table TO spatial_wfs_admin_usr;
GRANT DELETE ON mdsys.r_table TO spatial_wfs_admin_usr;
GRANT DEBUG ON mdsys.r_table TO spatial_wfs_admin_usr;
GRANT REFERENCES ON mdsys.r_table TO spatial_wfs_admin_usr;
GRANT ALTER ON mdsys.r_table TO spatial_wfs_admin_usr;
GRANT INDEX ON mdsys.r_table TO spatial_wfs_admin_usr;
GRANT READ ON mdsys.r_table TO spatial_wfs_admin_usr;
GRANT FLASHBACK ON mdsys.r_table TO spatial_wfs_admin_usr;
GRANT QUERY REWRITE ON mdsys.r_table TO spatial_wfs_admin_usr;
GRANT ON COMMIT REFRESH ON mdsys.r_table TO spatial_wfs_admin_usr;
GRANT SELECT ON mdsys.rowtokenmap$ TO spatial_wfs_admin_usr;
GRANT INSERT ON mdsys.rowtokenmap$ TO spatial_wfs_admin_usr;
GRANT UPDATE ON mdsys.rowtokenmap$ TO spatial_wfs_admin_usr;
GRANT DELETE ON mdsys.rowtokenmap$ TO spatial_wfs_admin_usr;
GRANT DEBUG ON mdsys.rowtokenmap$ TO spatial_wfs_admin_usr;
GRANT REFERENCES ON mdsys.rowtokenmap$ TO spatial_wfs_admin_usr;
GRANT READ ON mdsys.rowtokenmap$ TO spatial_wfs_admin_usr;
GRANT FLASHBACK ON mdsys.rowtokenmap$ TO spatial_wfs_admin_usr;
GRANT QUERY REWRITE ON mdsys.rowtokenmap$ TO spatial_wfs_admin_usr;
GRANT ON COMMIT REFRESH ON mdsys.rowtokenmap$ TO spatial_wfs_admin_usr;
GRANT MERGE VIEW ON mdsys.rowtokenmap$ TO spatial_wfs_admin_usr;
GRANT SELECT ON mdsys.rowtokenmap_t$ TO spatial_wfs_admin_usr;
GRANT INSERT ON mdsys.rowtokenmap_t$ TO spatial_wfs_admin_usr;
GRANT UPDATE ON mdsys.rowtokenmap_t$ TO spatial_wfs_admin_usr;
GRANT DELETE ON mdsys.rowtokenmap_t$ TO spatial_wfs_admin_usr;
GRANT DEBUG ON mdsys.rowtokenmap_t$ TO spatial_wfs_admin_usr;
GRANT REFERENCES ON mdsys.rowtokenmap_t$ TO spatial_wfs_admin_usr;
GRANT ALTER ON mdsys.rowtokenmap_t$ TO spatial_wfs_admin_usr;
GRANT INDEX ON mdsys.rowtokenmap_t$ TO spatial_wfs_admin_usr;
GRANT READ ON mdsys.rowtokenmap_t$ TO spatial_wfs_admin_usr;
GRANT FLASHBACK ON mdsys.rowtokenmap_t$ TO spatial_wfs_admin_usr;
GRANT QUERY REWRITE ON mdsys.rowtokenmap_t$ TO spatial_wfs_admin_usr;
GRANT ON COMMIT REFRESH ON mdsys.rowtokenmap_t$ TO spatial_wfs_admin_usr;
GRANT SELECT ON mdsys.token_sq$ TO spatial_wfs_admin_usr;
GRANT ALTER ON mdsys.token_sq$ TO spatial_wfs_admin_usr;
GRANT SELECT ON mdsys.tokensessionmap$ TO spatial_wfs_admin_usr;
GRANT INSERT ON mdsys.tokensessionmap$ TO spatial_wfs_admin_usr;
GRANT UPDATE ON mdsys.tokensessionmap$ TO spatial_wfs_admin_usr;
GRANT DELETE ON mdsys.tokensessionmap$ TO spatial_wfs_admin_usr;
GRANT DEBUG ON mdsys.tokensessionmap$ TO spatial_wfs_admin_usr;
GRANT REFERENCES ON mdsys.tokensessionmap$ TO spatial_wfs_admin_usr;
GRANT READ ON mdsys.tokensessionmap$ TO spatial_wfs_admin_usr;
GRANT FLASHBACK ON mdsys.tokensessionmap$ TO spatial_wfs_admin_usr;
GRANT QUERY REWRITE ON mdsys.tokensessionmap$ TO spatial_wfs_admin_usr;
GRANT ON COMMIT REFRESH ON mdsys.tokensessionmap$ TO spatial_wfs_admin_usr;
GRANT MERGE VIEW ON mdsys.tokensessionmap$ TO spatial_wfs_admin_usr;
GRANT SELECT ON mdsys.tokensessionmap_t$ TO spatial_wfs_admin_usr;
GRANT INSERT ON mdsys.tokensessionmap_t$ TO spatial_wfs_admin_usr;
GRANT UPDATE ON mdsys.tokensessionmap_t$ TO spatial_wfs_admin_usr;
GRANT DELETE ON mdsys.tokensessionmap_t$ TO spatial_wfs_admin_usr;
GRANT DEBUG ON mdsys.tokensessionmap_t$ TO spatial_wfs_admin_usr;
GRANT REFERENCES ON mdsys.tokensessionmap_t$ TO spatial_wfs_admin_usr;
GRANT ALTER ON mdsys.tokensessionmap_t$ TO spatial_wfs_admin_usr;
GRANT INDEX ON mdsys.tokensessionmap_t$ TO spatial_wfs_admin_usr;
GRANT READ ON mdsys.tokensessionmap_t$ TO spatial_wfs_admin_usr;
GRANT FLASHBACK ON mdsys.tokensessionmap_t$ TO spatial_wfs_admin_usr;
GRANT QUERY REWRITE ON mdsys.tokensessionmap_t$ TO spatial_wfs_admin_usr;
GRANT ON COMMIT REFRESH ON mdsys.tokensessionmap_t$ TO spatial_wfs_admin_usr;
GRANT SELECT ON mdsys.user_sdo_geom_metadata TO spatial_wfs_admin_usr;
GRANT INSERT ON mdsys.user_sdo_geom_metadata TO spatial_wfs_admin_usr;
GRANT UPDATE ON mdsys.user_sdo_geom_metadata TO spatial_wfs_admin_usr;
GRANT DELETE ON mdsys.user_sdo_geom_metadata TO spatial_wfs_admin_usr;
GRANT DEBUG ON mdsys.user_sdo_geom_metadata TO spatial_wfs_admin_usr;
GRANT REFERENCES ON mdsys.user_sdo_geom_metadata TO spatial_wfs_admin_usr;
GRANT READ ON mdsys.user_sdo_geom_metadata TO spatial_wfs_admin_usr;
GRANT FLASHBACK ON mdsys.user_sdo_geom_metadata TO spatial_wfs_admin_usr;
GRANT QUERY REWRITE ON mdsys.user_sdo_geom_metadata TO spatial_wfs_admin_usr;
GRANT ON COMMIT REFRESH ON mdsys.user_sdo_geom_metadata TO spatial_wfs_admin_usr;
GRANT MERGE VIEW ON mdsys.user_sdo_geom_metadata TO spatial_wfs_admin_usr;
GRANT SELECT ON mdsys.wfs_capabilitiesinfo$ TO spatial_wfs_admin_usr;
GRANT INSERT ON mdsys.wfs_capabilitiesinfo$ TO spatial_wfs_admin_usr;
GRANT UPDATE ON mdsys.wfs_capabilitiesinfo$ TO spatial_wfs_admin_usr;
GRANT DELETE ON mdsys.wfs_capabilitiesinfo$ TO spatial_wfs_admin_usr;
GRANT DEBUG ON mdsys.wfs_capabilitiesinfo$ TO spatial_wfs_admin_usr;
GRANT REFERENCES ON mdsys.wfs_capabilitiesinfo$ TO spatial_wfs_admin_usr;
GRANT ALTER ON mdsys.wfs_capabilitiesinfo$ TO spatial_wfs_admin_usr;
GRANT INDEX ON mdsys.wfs_capabilitiesinfo$ TO spatial_wfs_admin_usr;
GRANT READ ON mdsys.wfs_capabilitiesinfo$ TO spatial_wfs_admin_usr;
GRANT FLASHBACK ON mdsys.wfs_capabilitiesinfo$ TO spatial_wfs_admin_usr;
GRANT QUERY REWRITE ON mdsys.wfs_capabilitiesinfo$ TO spatial_wfs_admin_usr;
GRANT ON COMMIT REFRESH ON mdsys.wfs_capabilitiesinfo$ TO spatial_wfs_admin_usr;
GRANT SELECT ON mdsys.wfs_featureinstancemetadata$ TO spatial_wfs_admin_usr;
GRANT INSERT ON mdsys.wfs_featureinstancemetadata$ TO spatial_wfs_admin_usr;
GRANT UPDATE ON mdsys.wfs_featureinstancemetadata$ TO spatial_wfs_admin_usr;
GRANT DELETE ON mdsys.wfs_featureinstancemetadata$ TO spatial_wfs_admin_usr;
GRANT DEBUG ON mdsys.wfs_featureinstancemetadata$ TO spatial_wfs_admin_usr;
GRANT REFERENCES ON mdsys.wfs_featureinstancemetadata$ TO spatial_wfs_admin_usr;
GRANT ALTER ON mdsys.wfs_featureinstancemetadata$ TO spatial_wfs_admin_usr;
GRANT INDEX ON mdsys.wfs_featureinstancemetadata$ TO spatial_wfs_admin_usr;
GRANT READ ON mdsys.wfs_featureinstancemetadata$ TO spatial_wfs_admin_usr;
GRANT FLASHBACK ON mdsys.wfs_featureinstancemetadata$ TO spatial_wfs_admin_usr;
GRANT QUERY REWRITE ON mdsys.wfs_featureinstancemetadata$ TO spatial_wfs_admin_usr;
GRANT ON COMMIT REFRESH ON mdsys.wfs_featureinstancemetadata$ TO spatial_wfs_admin_usr;
GRANT SELECT ON mdsys.wfs_featuretablemdupdated$ TO spatial_wfs_admin_usr;
GRANT INSERT ON mdsys.wfs_featuretablemdupdated$ TO spatial_wfs_admin_usr;
GRANT UPDATE ON mdsys.wfs_featuretablemdupdated$ TO spatial_wfs_admin_usr;
GRANT DELETE ON mdsys.wfs_featuretablemdupdated$ TO spatial_wfs_admin_usr;
GRANT DEBUG ON mdsys.wfs_featuretablemdupdated$ TO spatial_wfs_admin_usr;
GRANT REFERENCES ON mdsys.wfs_featuretablemdupdated$ TO spatial_wfs_admin_usr;
GRANT ALTER ON mdsys.wfs_featuretablemdupdated$ TO spatial_wfs_admin_usr;
GRANT INDEX ON mdsys.wfs_featuretablemdupdated$ TO spatial_wfs_admin_usr;
GRANT READ ON mdsys.wfs_featuretablemdupdated$ TO spatial_wfs_admin_usr;
GRANT FLASHBACK ON mdsys.wfs_featuretablemdupdated$ TO spatial_wfs_admin_usr;
GRANT QUERY REWRITE ON mdsys.wfs_featuretablemdupdated$ TO spatial_wfs_admin_usr;
GRANT ON COMMIT REFRESH ON mdsys.wfs_featuretablemdupdated$ TO spatial_wfs_admin_usr;
GRANT SELECT ON mdsys.wfs_featuretableupdated$ TO spatial_wfs_admin_usr;
GRANT INSERT ON mdsys.wfs_featuretableupdated$ TO spatial_wfs_admin_usr;
GRANT UPDATE ON mdsys.wfs_featuretableupdated$ TO spatial_wfs_admin_usr;
GRANT DELETE ON mdsys.wfs_featuretableupdated$ TO spatial_wfs_admin_usr;
GRANT DEBUG ON mdsys.wfs_featuretableupdated$ TO spatial_wfs_admin_usr;
GRANT REFERENCES ON mdsys.wfs_featuretableupdated$ TO spatial_wfs_admin_usr;
GRANT ALTER ON mdsys.wfs_featuretableupdated$ TO spatial_wfs_admin_usr;
GRANT INDEX ON mdsys.wfs_featuretableupdated$ TO spatial_wfs_admin_usr;
GRANT READ ON mdsys.wfs_featuretableupdated$ TO spatial_wfs_admin_usr;
GRANT FLASHBACK ON mdsys.wfs_featuretableupdated$ TO spatial_wfs_admin_usr;
GRANT QUERY REWRITE ON mdsys.wfs_featuretableupdated$ TO spatial_wfs_admin_usr;
GRANT ON COMMIT REFRESH ON mdsys.wfs_featuretableupdated$ TO spatial_wfs_admin_usr;
GRANT SELECT ON mdsys.wfs_featuretype$ TO spatial_wfs_admin_usr;
GRANT INSERT ON mdsys.wfs_featuretype$ TO spatial_wfs_admin_usr;
GRANT UPDATE ON mdsys.wfs_featuretype$ TO spatial_wfs_admin_usr;
GRANT DELETE ON mdsys.wfs_featuretype$ TO spatial_wfs_admin_usr;
GRANT DEBUG ON mdsys.wfs_featuretype$ TO spatial_wfs_admin_usr;
GRANT REFERENCES ON mdsys.wfs_featuretype$ TO spatial_wfs_admin_usr;
GRANT ALTER ON mdsys.wfs_featuretype$ TO spatial_wfs_admin_usr;
GRANT INDEX ON mdsys.wfs_featuretype$ TO spatial_wfs_admin_usr;
GRANT READ ON mdsys.wfs_featuretype$ TO spatial_wfs_admin_usr;
GRANT FLASHBACK ON mdsys.wfs_featuretype$ TO spatial_wfs_admin_usr;
GRANT QUERY REWRITE ON mdsys.wfs_featuretype$ TO spatial_wfs_admin_usr;
GRANT ON COMMIT REFRESH ON mdsys.wfs_featuretype$ TO spatial_wfs_admin_usr;
GRANT SELECT ON mdsys.wfs_featuretypeattrs$ TO spatial_wfs_admin_usr;
GRANT INSERT ON mdsys.wfs_featuretypeattrs$ TO spatial_wfs_admin_usr;
GRANT UPDATE ON mdsys.wfs_featuretypeattrs$ TO spatial_wfs_admin_usr;
GRANT DELETE ON mdsys.wfs_featuretypeattrs$ TO spatial_wfs_admin_usr;
GRANT DEBUG ON mdsys.wfs_featuretypeattrs$ TO spatial_wfs_admin_usr;
GRANT REFERENCES ON mdsys.wfs_featuretypeattrs$ TO spatial_wfs_admin_usr;
GRANT ALTER ON mdsys.wfs_featuretypeattrs$ TO spatial_wfs_admin_usr;
GRANT INDEX ON mdsys.wfs_featuretypeattrs$ TO spatial_wfs_admin_usr;
GRANT READ ON mdsys.wfs_featuretypeattrs$ TO spatial_wfs_admin_usr;
GRANT FLASHBACK ON mdsys.wfs_featuretypeattrs$ TO spatial_wfs_admin_usr;
GRANT QUERY REWRITE ON mdsys.wfs_featuretypeattrs$ TO spatial_wfs_admin_usr;
GRANT ON COMMIT REFRESH ON mdsys.wfs_featuretypeattrs$ TO spatial_wfs_admin_usr;
GRANT SELECT ON mdsys.wfs_featuretypecomplextags$ TO spatial_wfs_admin_usr;
GRANT INSERT ON mdsys.wfs_featuretypecomplextags$ TO spatial_wfs_admin_usr;
GRANT UPDATE ON mdsys.wfs_featuretypecomplextags$ TO spatial_wfs_admin_usr;
GRANT DELETE ON mdsys.wfs_featuretypecomplextags$ TO spatial_wfs_admin_usr;
GRANT DEBUG ON mdsys.wfs_featuretypecomplextags$ TO spatial_wfs_admin_usr;
GRANT REFERENCES ON mdsys.wfs_featuretypecomplextags$ TO spatial_wfs_admin_usr;
GRANT ALTER ON mdsys.wfs_featuretypecomplextags$ TO spatial_wfs_admin_usr;
GRANT INDEX ON mdsys.wfs_featuretypecomplextags$ TO spatial_wfs_admin_usr;
GRANT READ ON mdsys.wfs_featuretypecomplextags$ TO spatial_wfs_admin_usr;
GRANT FLASHBACK ON mdsys.wfs_featuretypecomplextags$ TO spatial_wfs_admin_usr;
GRANT QUERY REWRITE ON mdsys.wfs_featuretypecomplextags$ TO spatial_wfs_admin_usr;
GRANT ON COMMIT REFRESH ON mdsys.wfs_featuretypecomplextags$ TO spatial_wfs_admin_usr;
GRANT SELECT ON mdsys.wfs_featuretypenestedsdos$ TO spatial_wfs_admin_usr;
GRANT INSERT ON mdsys.wfs_featuretypenestedsdos$ TO spatial_wfs_admin_usr;
GRANT UPDATE ON mdsys.wfs_featuretypenestedsdos$ TO spatial_wfs_admin_usr;
GRANT DELETE ON mdsys.wfs_featuretypenestedsdos$ TO spatial_wfs_admin_usr;
GRANT DEBUG ON mdsys.wfs_featuretypenestedsdos$ TO spatial_wfs_admin_usr;
GRANT REFERENCES ON mdsys.wfs_featuretypenestedsdos$ TO spatial_wfs_admin_usr;
GRANT ALTER ON mdsys.wfs_featuretypenestedsdos$ TO spatial_wfs_admin_usr;
GRANT INDEX ON mdsys.wfs_featuretypenestedsdos$ TO spatial_wfs_admin_usr;
GRANT READ ON mdsys.wfs_featuretypenestedsdos$ TO spatial_wfs_admin_usr;
GRANT FLASHBACK ON mdsys.wfs_featuretypenestedsdos$ TO spatial_wfs_admin_usr;
GRANT QUERY REWRITE ON mdsys.wfs_featuretypenestedsdos$ TO spatial_wfs_admin_usr;
GRANT ON COMMIT REFRESH ON mdsys.wfs_featuretypenestedsdos$ TO spatial_wfs_admin_usr;
GRANT SELECT ON mdsys.wfs_featuretypesimpletagattrs$ TO spatial_wfs_admin_usr;
GRANT INSERT ON mdsys.wfs_featuretypesimpletagattrs$ TO spatial_wfs_admin_usr;
GRANT UPDATE ON mdsys.wfs_featuretypesimpletagattrs$ TO spatial_wfs_admin_usr;
GRANT DELETE ON mdsys.wfs_featuretypesimpletagattrs$ TO spatial_wfs_admin_usr;
GRANT DEBUG ON mdsys.wfs_featuretypesimpletagattrs$ TO spatial_wfs_admin_usr;
GRANT REFERENCES ON mdsys.wfs_featuretypesimpletagattrs$ TO spatial_wfs_admin_usr;
GRANT ALTER ON mdsys.wfs_featuretypesimpletagattrs$ TO spatial_wfs_admin_usr;
GRANT INDEX ON mdsys.wfs_featuretypesimpletagattrs$ TO spatial_wfs_admin_usr;
GRANT READ ON mdsys.wfs_featuretypesimpletagattrs$ TO spatial_wfs_admin_usr;
GRANT FLASHBACK ON mdsys.wfs_featuretypesimpletagattrs$ TO spatial_wfs_admin_usr;
GRANT QUERY REWRITE ON mdsys.wfs_featuretypesimpletagattrs$ TO spatial_wfs_admin_usr;
GRANT ON COMMIT REFRESH ON mdsys.wfs_featuretypesimpletagattrs$ TO spatial_wfs_admin_usr;
GRANT SELECT ON mdsys.wfs_featuretypetags$ TO spatial_wfs_admin_usr;
GRANT INSERT ON mdsys.wfs_featuretypetags$ TO spatial_wfs_admin_usr;
GRANT UPDATE ON mdsys.wfs_featuretypetags$ TO spatial_wfs_admin_usr;
GRANT DELETE ON mdsys.wfs_featuretypetags$ TO spatial_wfs_admin_usr;
GRANT DEBUG ON mdsys.wfs_featuretypetags$ TO spatial_wfs_admin_usr;
GRANT REFERENCES ON mdsys.wfs_featuretypetags$ TO spatial_wfs_admin_usr;
GRANT ALTER ON mdsys.wfs_featuretypetags$ TO spatial_wfs_admin_usr;
GRANT INDEX ON mdsys.wfs_featuretypetags$ TO spatial_wfs_admin_usr;
GRANT READ ON mdsys.wfs_featuretypetags$ TO spatial_wfs_admin_usr;
GRANT FLASHBACK ON mdsys.wfs_featuretypetags$ TO spatial_wfs_admin_usr;
GRANT QUERY REWRITE ON mdsys.wfs_featuretypetags$ TO spatial_wfs_admin_usr;
GRANT ON COMMIT REFRESH ON mdsys.wfs_featuretypetags$ TO spatial_wfs_admin_usr;
GRANT SELECT ON mdsys.wfs_featuretypexmlcolinfo$ TO spatial_wfs_admin_usr;
GRANT INSERT ON mdsys.wfs_featuretypexmlcolinfo$ TO spatial_wfs_admin_usr;
GRANT UPDATE ON mdsys.wfs_featuretypexmlcolinfo$ TO spatial_wfs_admin_usr;
GRANT DELETE ON mdsys.wfs_featuretypexmlcolinfo$ TO spatial_wfs_admin_usr;
GRANT DEBUG ON mdsys.wfs_featuretypexmlcolinfo$ TO spatial_wfs_admin_usr;
GRANT REFERENCES ON mdsys.wfs_featuretypexmlcolinfo$ TO spatial_wfs_admin_usr;
GRANT ALTER ON mdsys.wfs_featuretypexmlcolinfo$ TO spatial_wfs_admin_usr;
GRANT INDEX ON mdsys.wfs_featuretypexmlcolinfo$ TO spatial_wfs_admin_usr;
GRANT READ ON mdsys.wfs_featuretypexmlcolinfo$ TO spatial_wfs_admin_usr;
GRANT FLASHBACK ON mdsys.wfs_featuretypexmlcolinfo$ TO spatial_wfs_admin_usr;
GRANT QUERY REWRITE ON mdsys.wfs_featuretypexmlcolinfo$ TO spatial_wfs_admin_usr;
GRANT ON COMMIT REFRESH ON mdsys.wfs_featuretypexmlcolinfo$ TO spatial_wfs_admin_usr;
GRANT SELECT ON mdsys.wfs_fttypecomplextagattrs$ TO spatial_wfs_admin_usr;
GRANT INSERT ON mdsys.wfs_fttypecomplextagattrs$ TO spatial_wfs_admin_usr;
GRANT UPDATE ON mdsys.wfs_fttypecomplextagattrs$ TO spatial_wfs_admin_usr;
GRANT DELETE ON mdsys.wfs_fttypecomplextagattrs$ TO spatial_wfs_admin_usr;
GRANT DEBUG ON mdsys.wfs_fttypecomplextagattrs$ TO spatial_wfs_admin_usr;
GRANT REFERENCES ON mdsys.wfs_fttypecomplextagattrs$ TO spatial_wfs_admin_usr;
GRANT ALTER ON mdsys.wfs_fttypecomplextagattrs$ TO spatial_wfs_admin_usr;
GRANT INDEX ON mdsys.wfs_fttypecomplextagattrs$ TO spatial_wfs_admin_usr;
GRANT READ ON mdsys.wfs_fttypecomplextagattrs$ TO spatial_wfs_admin_usr;
GRANT FLASHBACK ON mdsys.wfs_fttypecomplextagattrs$ TO spatial_wfs_admin_usr;
GRANT QUERY REWRITE ON mdsys.wfs_fttypecomplextagattrs$ TO spatial_wfs_admin_usr;
GRANT ON COMMIT REFRESH ON mdsys.wfs_fttypecomplextagattrs$ TO spatial_wfs_admin_usr;
GRANT SELECT ON mdsys.wfs_ftxsdinfo$ TO spatial_wfs_admin_usr;
GRANT INSERT ON mdsys.wfs_ftxsdinfo$ TO spatial_wfs_admin_usr;
GRANT UPDATE ON mdsys.wfs_ftxsdinfo$ TO spatial_wfs_admin_usr;
GRANT DELETE ON mdsys.wfs_ftxsdinfo$ TO spatial_wfs_admin_usr;
GRANT DEBUG ON mdsys.wfs_ftxsdinfo$ TO spatial_wfs_admin_usr;
GRANT REFERENCES ON mdsys.wfs_ftxsdinfo$ TO spatial_wfs_admin_usr;
GRANT ALTER ON mdsys.wfs_ftxsdinfo$ TO spatial_wfs_admin_usr;
GRANT INDEX ON mdsys.wfs_ftxsdinfo$ TO spatial_wfs_admin_usr;
GRANT READ ON mdsys.wfs_ftxsdinfo$ TO spatial_wfs_admin_usr;
GRANT FLASHBACK ON mdsys.wfs_ftxsdinfo$ TO spatial_wfs_admin_usr;
GRANT QUERY REWRITE ON mdsys.wfs_ftxsdinfo$ TO spatial_wfs_admin_usr;
GRANT ON COMMIT REFRESH ON mdsys.wfs_ftxsdinfo$ TO spatial_wfs_admin_usr;
GRANT SELECT ON mdsys.wfs_proc_map$ TO spatial_wfs_admin_usr;
GRANT INSERT ON mdsys.wfs_proc_map$ TO spatial_wfs_admin_usr;
GRANT UPDATE ON mdsys.wfs_proc_map$ TO spatial_wfs_admin_usr;
GRANT DELETE ON mdsys.wfs_proc_map$ TO spatial_wfs_admin_usr;
GRANT DEBUG ON mdsys.wfs_proc_map$ TO spatial_wfs_admin_usr;
GRANT REFERENCES ON mdsys.wfs_proc_map$ TO spatial_wfs_admin_usr;
GRANT ALTER ON mdsys.wfs_proc_map$ TO spatial_wfs_admin_usr;
GRANT INDEX ON mdsys.wfs_proc_map$ TO spatial_wfs_admin_usr;
GRANT READ ON mdsys.wfs_proc_map$ TO spatial_wfs_admin_usr;
GRANT FLASHBACK ON mdsys.wfs_proc_map$ TO spatial_wfs_admin_usr;
GRANT QUERY REWRITE ON mdsys.wfs_proc_map$ TO spatial_wfs_admin_usr;
GRANT ON COMMIT REFRESH ON mdsys.wfs_proc_map$ TO spatial_wfs_admin_usr;
GRANT SELECT ON mdsys.wfs_proc_sq$ TO spatial_wfs_admin_usr;
GRANT ALTER ON mdsys.wfs_proc_sq$ TO spatial_wfs_admin_usr;
GRANT SELECT ON mdsys.wfs_srs$ TO spatial_wfs_admin_usr;
GRANT INSERT ON mdsys.wfs_srs$ TO spatial_wfs_admin_usr;
GRANT UPDATE ON mdsys.wfs_srs$ TO spatial_wfs_admin_usr;
GRANT DELETE ON mdsys.wfs_srs$ TO spatial_wfs_admin_usr;
GRANT DEBUG ON mdsys.wfs_srs$ TO spatial_wfs_admin_usr;
GRANT REFERENCES ON mdsys.wfs_srs$ TO spatial_wfs_admin_usr;
GRANT ALTER ON mdsys.wfs_srs$ TO spatial_wfs_admin_usr;
GRANT INDEX ON mdsys.wfs_srs$ TO spatial_wfs_admin_usr;
GRANT READ ON mdsys.wfs_srs$ TO spatial_wfs_admin_usr;
GRANT FLASHBACK ON mdsys.wfs_srs$ TO spatial_wfs_admin_usr;
GRANT QUERY REWRITE ON mdsys.wfs_srs$ TO spatial_wfs_admin_usr;
GRANT ON COMMIT REFRESH ON mdsys.wfs_srs$ TO spatial_wfs_admin_usr;
GRANT SELECT ON mdsys.wfs_trg_table_temp$ TO spatial_wfs_admin_usr;
GRANT INSERT ON mdsys.wfs_trg_table_temp$ TO spatial_wfs_admin_usr;
GRANT UPDATE ON mdsys.wfs_trg_table_temp$ TO spatial_wfs_admin_usr;
GRANT DELETE ON mdsys.wfs_trg_table_temp$ TO spatial_wfs_admin_usr;
GRANT DEBUG ON mdsys.wfs_trg_table_temp$ TO spatial_wfs_admin_usr;
GRANT REFERENCES ON mdsys.wfs_trg_table_temp$ TO spatial_wfs_admin_usr;
GRANT ALTER ON mdsys.wfs_trg_table_temp$ TO spatial_wfs_admin_usr;
GRANT INDEX ON mdsys.wfs_trg_table_temp$ TO spatial_wfs_admin_usr;
GRANT READ ON mdsys.wfs_trg_table_temp$ TO spatial_wfs_admin_usr;
GRANT FLASHBACK ON mdsys.wfs_trg_table_temp$ TO spatial_wfs_admin_usr;
GRANT QUERY REWRITE ON mdsys.wfs_trg_table_temp$ TO spatial_wfs_admin_usr;
GRANT ON COMMIT REFRESH ON mdsys.wfs_trg_table_temp$ TO spatial_wfs_admin_usr;
GRANT SELECT ON mdsys.xmlinfo_sq$ TO spatial_wfs_admin_usr;
GRANT ALTER ON mdsys.xmlinfo_sq$ TO spatial_wfs_admin_usr;