GRANT SELECT ON mdsys.csw_capabilitiesinfo$ TO spatial_csw_admin;
GRANT INSERT ON mdsys.csw_capabilitiesinfo$ TO spatial_csw_admin;
GRANT UPDATE ON mdsys.csw_capabilitiesinfo$ TO spatial_csw_admin;
GRANT DELETE ON mdsys.csw_capabilitiesinfo$ TO spatial_csw_admin;
GRANT DEBUG ON mdsys.csw_capabilitiesinfo$ TO spatial_csw_admin;
GRANT ALTER ON mdsys.csw_capabilitiesinfo$ TO spatial_csw_admin;
GRANT READ ON mdsys.csw_capabilitiesinfo$ TO spatial_csw_admin;
GRANT FLASHBACK ON mdsys.csw_capabilitiesinfo$ TO spatial_csw_admin;
GRANT QUERY REWRITE ON mdsys.csw_capabilitiesinfo$ TO spatial_csw_admin;
GRANT ON COMMIT REFRESH ON mdsys.csw_capabilitiesinfo$ TO spatial_csw_admin;
GRANT SELECT ON mdsys.csw_domaininfo$ TO spatial_csw_admin;
GRANT INSERT ON mdsys.csw_domaininfo$ TO spatial_csw_admin;
GRANT UPDATE ON mdsys.csw_domaininfo$ TO spatial_csw_admin;
GRANT DELETE ON mdsys.csw_domaininfo$ TO spatial_csw_admin;
GRANT DEBUG ON mdsys.csw_domaininfo$ TO spatial_csw_admin;
GRANT ALTER ON mdsys.csw_domaininfo$ TO spatial_csw_admin;
GRANT READ ON mdsys.csw_domaininfo$ TO spatial_csw_admin;
GRANT FLASHBACK ON mdsys.csw_domaininfo$ TO spatial_csw_admin;
GRANT QUERY REWRITE ON mdsys.csw_domaininfo$ TO spatial_csw_admin;
GRANT ON COMMIT REFRESH ON mdsys.csw_domaininfo$ TO spatial_csw_admin;
GRANT SELECT ON mdsys.csw_harvestmetadata$ TO spatial_csw_admin;
GRANT INSERT ON mdsys.csw_harvestmetadata$ TO spatial_csw_admin;
GRANT UPDATE ON mdsys.csw_harvestmetadata$ TO spatial_csw_admin;
GRANT DELETE ON mdsys.csw_harvestmetadata$ TO spatial_csw_admin;
GRANT DEBUG ON mdsys.csw_harvestmetadata$ TO spatial_csw_admin;
GRANT ALTER ON mdsys.csw_harvestmetadata$ TO spatial_csw_admin;
GRANT READ ON mdsys.csw_harvestmetadata$ TO spatial_csw_admin;
GRANT FLASHBACK ON mdsys.csw_harvestmetadata$ TO spatial_csw_admin;
GRANT QUERY REWRITE ON mdsys.csw_harvestmetadata$ TO spatial_csw_admin;
GRANT ON COMMIT REFRESH ON mdsys.csw_harvestmetadata$ TO spatial_csw_admin;
GRANT SELECT ON mdsys.csw_plugin_map$ TO spatial_csw_admin;
GRANT INSERT ON mdsys.csw_plugin_map$ TO spatial_csw_admin;
GRANT UPDATE ON mdsys.csw_plugin_map$ TO spatial_csw_admin;
GRANT DELETE ON mdsys.csw_plugin_map$ TO spatial_csw_admin;
GRANT DEBUG ON mdsys.csw_plugin_map$ TO spatial_csw_admin;
GRANT ALTER ON mdsys.csw_plugin_map$ TO spatial_csw_admin;
GRANT READ ON mdsys.csw_plugin_map$ TO spatial_csw_admin;
GRANT FLASHBACK ON mdsys.csw_plugin_map$ TO spatial_csw_admin;
GRANT QUERY REWRITE ON mdsys.csw_plugin_map$ TO spatial_csw_admin;
GRANT ON COMMIT REFRESH ON mdsys.csw_plugin_map$ TO spatial_csw_admin;
GRANT SELECT ON mdsys.csw_record_types$ TO spatial_csw_admin;
GRANT INSERT ON mdsys.csw_record_types$ TO spatial_csw_admin;
GRANT UPDATE ON mdsys.csw_record_types$ TO spatial_csw_admin;
GRANT DELETE ON mdsys.csw_record_types$ TO spatial_csw_admin;
GRANT DEBUG ON mdsys.csw_record_types$ TO spatial_csw_admin;
GRANT ALTER ON mdsys.csw_record_types$ TO spatial_csw_admin;
GRANT READ ON mdsys.csw_record_types$ TO spatial_csw_admin;
GRANT FLASHBACK ON mdsys.csw_record_types$ TO spatial_csw_admin;
GRANT QUERY REWRITE ON mdsys.csw_record_types$ TO spatial_csw_admin;
GRANT ON COMMIT REFRESH ON mdsys.csw_record_types$ TO spatial_csw_admin;
GRANT SELECT ON mdsys.csw_recorddomainupdated$ TO spatial_csw_admin;
GRANT INSERT ON mdsys.csw_recorddomainupdated$ TO spatial_csw_admin;
GRANT UPDATE ON mdsys.csw_recorddomainupdated$ TO spatial_csw_admin;
GRANT DELETE ON mdsys.csw_recorddomainupdated$ TO spatial_csw_admin;
GRANT DEBUG ON mdsys.csw_recorddomainupdated$ TO spatial_csw_admin;
GRANT ALTER ON mdsys.csw_recorddomainupdated$ TO spatial_csw_admin;
GRANT READ ON mdsys.csw_recorddomainupdated$ TO spatial_csw_admin;
GRANT FLASHBACK ON mdsys.csw_recorddomainupdated$ TO spatial_csw_admin;
GRANT QUERY REWRITE ON mdsys.csw_recorddomainupdated$ TO spatial_csw_admin;
GRANT ON COMMIT REFRESH ON mdsys.csw_recorddomainupdated$ TO spatial_csw_admin;
GRANT SELECT ON mdsys.csw_recordtablemdupdated$ TO spatial_csw_admin;
GRANT INSERT ON mdsys.csw_recordtablemdupdated$ TO spatial_csw_admin;
GRANT UPDATE ON mdsys.csw_recordtablemdupdated$ TO spatial_csw_admin;
GRANT DELETE ON mdsys.csw_recordtablemdupdated$ TO spatial_csw_admin;
GRANT DEBUG ON mdsys.csw_recordtablemdupdated$ TO spatial_csw_admin;
GRANT ALTER ON mdsys.csw_recordtablemdupdated$ TO spatial_csw_admin;
GRANT READ ON mdsys.csw_recordtablemdupdated$ TO spatial_csw_admin;
GRANT FLASHBACK ON mdsys.csw_recordtablemdupdated$ TO spatial_csw_admin;
GRANT QUERY REWRITE ON mdsys.csw_recordtablemdupdated$ TO spatial_csw_admin;
GRANT ON COMMIT REFRESH ON mdsys.csw_recordtablemdupdated$ TO spatial_csw_admin;
GRANT SELECT ON mdsys.csw_recordtableupdated$ TO spatial_csw_admin;
GRANT INSERT ON mdsys.csw_recordtableupdated$ TO spatial_csw_admin;
GRANT UPDATE ON mdsys.csw_recordtableupdated$ TO spatial_csw_admin;
GRANT DELETE ON mdsys.csw_recordtableupdated$ TO spatial_csw_admin;
GRANT DEBUG ON mdsys.csw_recordtableupdated$ TO spatial_csw_admin;
GRANT ALTER ON mdsys.csw_recordtableupdated$ TO spatial_csw_admin;
GRANT READ ON mdsys.csw_recordtableupdated$ TO spatial_csw_admin;
GRANT FLASHBACK ON mdsys.csw_recordtableupdated$ TO spatial_csw_admin;
GRANT QUERY REWRITE ON mdsys.csw_recordtableupdated$ TO spatial_csw_admin;
GRANT ON COMMIT REFRESH ON mdsys.csw_recordtableupdated$ TO spatial_csw_admin;
GRANT SELECT ON mdsys.csw_recordviewmap$ TO spatial_csw_admin;
GRANT INSERT ON mdsys.csw_recordviewmap$ TO spatial_csw_admin;
GRANT UPDATE ON mdsys.csw_recordviewmap$ TO spatial_csw_admin;
GRANT DELETE ON mdsys.csw_recordviewmap$ TO spatial_csw_admin;
GRANT DEBUG ON mdsys.csw_recordviewmap$ TO spatial_csw_admin;
GRANT ALTER ON mdsys.csw_recordviewmap$ TO spatial_csw_admin;
GRANT READ ON mdsys.csw_recordviewmap$ TO spatial_csw_admin;
GRANT FLASHBACK ON mdsys.csw_recordviewmap$ TO spatial_csw_admin;
GRANT QUERY REWRITE ON mdsys.csw_recordviewmap$ TO spatial_csw_admin;
GRANT ON COMMIT REFRESH ON mdsys.csw_recordviewmap$ TO spatial_csw_admin;
GRANT SELECT ON mdsys.csw_rtxsdinfo$ TO spatial_csw_admin;
GRANT INSERT ON mdsys.csw_rtxsdinfo$ TO spatial_csw_admin;
GRANT UPDATE ON mdsys.csw_rtxsdinfo$ TO spatial_csw_admin;
GRANT DELETE ON mdsys.csw_rtxsdinfo$ TO spatial_csw_admin;
GRANT DEBUG ON mdsys.csw_rtxsdinfo$ TO spatial_csw_admin;
GRANT ALTER ON mdsys.csw_rtxsdinfo$ TO spatial_csw_admin;
GRANT READ ON mdsys.csw_rtxsdinfo$ TO spatial_csw_admin;
GRANT FLASHBACK ON mdsys.csw_rtxsdinfo$ TO spatial_csw_admin;
GRANT QUERY REWRITE ON mdsys.csw_rtxsdinfo$ TO spatial_csw_admin;
GRANT ON COMMIT REFRESH ON mdsys.csw_rtxsdinfo$ TO spatial_csw_admin;
GRANT SELECT ON mdsys.csw_trg_table_temp$ TO spatial_csw_admin;
GRANT INSERT ON mdsys.csw_trg_table_temp$ TO spatial_csw_admin;
GRANT UPDATE ON mdsys.csw_trg_table_temp$ TO spatial_csw_admin;
GRANT DELETE ON mdsys.csw_trg_table_temp$ TO spatial_csw_admin;
GRANT DEBUG ON mdsys.csw_trg_table_temp$ TO spatial_csw_admin;
GRANT ALTER ON mdsys.csw_trg_table_temp$ TO spatial_csw_admin;
GRANT READ ON mdsys.csw_trg_table_temp$ TO spatial_csw_admin;
GRANT FLASHBACK ON mdsys.csw_trg_table_temp$ TO spatial_csw_admin;
GRANT QUERY REWRITE ON mdsys.csw_trg_table_temp$ TO spatial_csw_admin;
GRANT ON COMMIT REFRESH ON mdsys.csw_trg_table_temp$ TO spatial_csw_admin;
GRANT SELECT ON mdsys.ro_table TO spatial_csw_admin;
GRANT INSERT ON mdsys.ro_table TO spatial_csw_admin;
GRANT UPDATE ON mdsys.ro_table TO spatial_csw_admin;
GRANT DELETE ON mdsys.ro_table TO spatial_csw_admin;
GRANT DEBUG ON mdsys.ro_table TO spatial_csw_admin;
GRANT ALTER ON mdsys.ro_table TO spatial_csw_admin;
GRANT READ ON mdsys.ro_table TO spatial_csw_admin;
GRANT FLASHBACK ON mdsys.ro_table TO spatial_csw_admin;
GRANT QUERY REWRITE ON mdsys.ro_table TO spatial_csw_admin;
GRANT ON COMMIT REFRESH ON mdsys.ro_table TO spatial_csw_admin;
GRANT SELECT ON mdsys.rt_sq$ TO spatial_csw_admin;
GRANT ALTER ON mdsys.rt_sq$ TO spatial_csw_admin;
GRANT SELECT ON mdsys.user_sdo_geom_metadata TO spatial_csw_admin;
GRANT INSERT ON mdsys.user_sdo_geom_metadata TO spatial_csw_admin;
GRANT UPDATE ON mdsys.user_sdo_geom_metadata TO spatial_csw_admin;
GRANT DELETE ON mdsys.user_sdo_geom_metadata TO spatial_csw_admin;
GRANT DEBUG ON mdsys.user_sdo_geom_metadata TO spatial_csw_admin;
GRANT READ ON mdsys.user_sdo_geom_metadata TO spatial_csw_admin;
GRANT FLASHBACK ON mdsys.user_sdo_geom_metadata TO spatial_csw_admin;
GRANT QUERY REWRITE ON mdsys.user_sdo_geom_metadata TO spatial_csw_admin;
GRANT ON COMMIT REFRESH ON mdsys.user_sdo_geom_metadata TO spatial_csw_admin;
GRANT MERGE VIEW ON mdsys.user_sdo_geom_metadata TO spatial_csw_admin;