GRANT SELECT ON mdsys.currentsessiontokenmap$ TO wfs_usr_role;
GRANT INSERT ON mdsys.currentsessiontokenmap$ TO wfs_usr_role;
GRANT UPDATE ON mdsys.currentsessiontokenmap$ TO wfs_usr_role;
GRANT DELETE ON mdsys.currentsessiontokenmap$ TO wfs_usr_role;
GRANT DEBUG ON mdsys.currentsessiontokenmap$ TO wfs_usr_role;
GRANT READ ON mdsys.currentsessiontokenmap$ TO wfs_usr_role;
GRANT FLASHBACK ON mdsys.currentsessiontokenmap$ TO wfs_usr_role;
GRANT QUERY REWRITE ON mdsys.currentsessiontokenmap$ TO wfs_usr_role;
GRANT ON COMMIT REFRESH ON mdsys.currentsessiontokenmap$ TO wfs_usr_role;
GRANT MERGE VIEW ON mdsys.currentsessiontokenmap$ TO wfs_usr_role;
GRANT SELECT ON mdsys.r_table TO wfs_usr_role;
GRANT SELECT ON mdsys.rowtokenmap$ TO wfs_usr_role;
GRANT INSERT ON mdsys.rowtokenmap$ TO wfs_usr_role;
GRANT UPDATE ON mdsys.rowtokenmap$ TO wfs_usr_role;
GRANT DELETE ON mdsys.rowtokenmap$ TO wfs_usr_role;
GRANT DEBUG ON mdsys.rowtokenmap$ TO wfs_usr_role;
GRANT READ ON mdsys.rowtokenmap$ TO wfs_usr_role;
GRANT FLASHBACK ON mdsys.rowtokenmap$ TO wfs_usr_role;
GRANT QUERY REWRITE ON mdsys.rowtokenmap$ TO wfs_usr_role;
GRANT ON COMMIT REFRESH ON mdsys.rowtokenmap$ TO wfs_usr_role;
GRANT MERGE VIEW ON mdsys.rowtokenmap$ TO wfs_usr_role;
GRANT SELECT ON mdsys.tokensessionmap$ TO wfs_usr_role;
GRANT INSERT ON mdsys.tokensessionmap$ TO wfs_usr_role;
GRANT UPDATE ON mdsys.tokensessionmap$ TO wfs_usr_role;
GRANT DELETE ON mdsys.tokensessionmap$ TO wfs_usr_role;
GRANT DEBUG ON mdsys.tokensessionmap$ TO wfs_usr_role;
GRANT READ ON mdsys.tokensessionmap$ TO wfs_usr_role;
GRANT FLASHBACK ON mdsys.tokensessionmap$ TO wfs_usr_role;
GRANT QUERY REWRITE ON mdsys.tokensessionmap$ TO wfs_usr_role;
GRANT ON COMMIT REFRESH ON mdsys.tokensessionmap$ TO wfs_usr_role;
GRANT MERGE VIEW ON mdsys.tokensessionmap$ TO wfs_usr_role;
GRANT SELECT ON mdsys.user_sdo_geom_metadata TO wfs_usr_role;
GRANT SELECT ON mdsys.wfs_capabilitiesinfo$ TO wfs_usr_role;
GRANT SELECT ON mdsys.wfs_featureinstancemetadata$ TO wfs_usr_role;
GRANT SELECT ON mdsys.wfs_featuretablemdupdated$ TO wfs_usr_role;
GRANT SELECT ON mdsys.wfs_featuretableupdated$ TO wfs_usr_role;
GRANT SELECT ON mdsys.wfs_featuretype$ TO wfs_usr_role;
GRANT SELECT ON mdsys.wfs_featuretypeattrs$ TO wfs_usr_role;
GRANT SELECT ON mdsys.wfs_featuretypecomplextags$ TO wfs_usr_role;
GRANT SELECT ON mdsys.wfs_featuretypenestedsdos$ TO wfs_usr_role;
GRANT SELECT ON mdsys.wfs_featuretypesimpletagattrs$ TO wfs_usr_role;
GRANT SELECT ON mdsys.wfs_featuretypetags$ TO wfs_usr_role;
GRANT SELECT ON mdsys.wfs_featuretypexmlcolinfo$ TO wfs_usr_role;
GRANT SELECT ON mdsys.wfs_fttypecomplextagattrs$ TO wfs_usr_role;
GRANT SELECT ON mdsys.wfs_ftxsdinfo$ TO wfs_usr_role;
GRANT SELECT ON mdsys.wfs_proc_map$ TO wfs_usr_role;
GRANT SELECT ON mdsys.wfs_srs$ TO wfs_usr_role;
GRANT SELECT ON mdsys.wfs_trg_table_temp$ TO wfs_usr_role;
GRANT INSERT ON mdsys.wfs_trg_table_temp$ TO wfs_usr_role;
GRANT UPDATE ON mdsys.wfs_trg_table_temp$ TO wfs_usr_role;
GRANT DELETE ON mdsys.wfs_trg_table_temp$ TO wfs_usr_role;
GRANT DEBUG ON mdsys.wfs_trg_table_temp$ TO wfs_usr_role;
GRANT ALTER ON mdsys.wfs_trg_table_temp$ TO wfs_usr_role;
GRANT READ ON mdsys.wfs_trg_table_temp$ TO wfs_usr_role;
GRANT FLASHBACK ON mdsys.wfs_trg_table_temp$ TO wfs_usr_role;
GRANT QUERY REWRITE ON mdsys.wfs_trg_table_temp$ TO wfs_usr_role;
GRANT ON COMMIT REFRESH ON mdsys.wfs_trg_table_temp$ TO wfs_usr_role;