CREATE OR REPLACE NONEDITIONABLE FUNCTION mdsys.OGC_PolygonFromWKB(
  wkb   IN BLOB,
  srid  IN INTEGER DEFAULT NULL)
    RETURN ST_POLYGON IS
BEGIN
  RETURN TREAT(ST_GEOMETRY.FROM_WKB(wkb, srid) AS ST_POLYGON);
END OGC_PolygonFromWKB;
/