CREATE OR REPLACE NONEDITIONABLE FUNCTION mdsys.OGC_MultiPolygonFromText(
  wkt   IN VARCHAR2,
  srid  IN INTEGER DEFAULT NULL)
    RETURN ST_MULTIPOLYGON IS
BEGIN
  RETURN TREAT(ST_GEOMETRY.FROM_WKT(wkt, srid) AS ST_MULTIPOLYGON);
END OGC_MultiPolygonFromText;
/