CREATE OR REPLACE NONEDITIONABLE FUNCTION mdsys.OGC_PointFromWKB(
  wkb   IN BLOB,
  srid  IN INTEGER DEFAULT NULL)
    RETURN ST_Point IS
BEGIN
  RETURN TREAT(ST_GEOMETRY.FROM_WKB(wkb, srid) AS ST_Point);
END OGC_PointFromWKB;
/