CREATE OR REPLACE NONEDITIONABLE FUNCTION mdsys.OGC_MultiPolygonFromWKB(
  wkb   IN BLOB,
  srid  IN INTEGER DEFAULT NULL)
    RETURN ST_MULTIPOLYGON IS
BEGIN
  RETURN TREAT(ST_GEOMETRY.FROM_WKB(wkb, srid) AS ST_MULTIPOLYGON);
END OGC_MultiPolygonFromWKB;
/